package com.naviq.antlr4.oracle;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.Lexer;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.IntStream;
import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.Token;

import java.util.HashSet;
import java.util.Set;

/**
 * Java port of the Go {@code PlSqlLexerBase} (package {@code plsql}, generated alongside
 * PlSqlLexer.g4/PlSqlParser.g4 via antlr4-go) - base class required by PlSqlLexer.g4's
 * {@code options { superClass = PlSqlLexerBase; }} once the grammar is regenerated for the
 * Java ANTLR runtime (mirrors how {@link com.naviq.antlr4.oracle.PlSqlLexerBase} plays the same
 * role for the Postgres grammar).
 * <p>
 * Converted mechanically from the Go source (not hand-transcribed) to avoid transcription
 * errors in the ~2,300-entry non-reserved-keyword table inside {@link #isIdentifier(int)}.
 * <p>
 * NOTE ON {@link #isReservedKeywords(String)}: the Go source references a package-level
 * {@code ReservedWords} map that is declared elsewhere in the {@code plsql} Go package and was
 * NOT included in the file handed to this conversion - it must be supplied separately (a
 * {@code Set<String>} of reserved keyword text, uppercase) before this class is usable. See the
 * TODO on {@link #RESERVED_WORDS} below.
 */
public abstract class PlSqlLexerBase extends Lexer {
     protected final PlSqlLexerBase p = this;

    /**
     * TODO: populate with the actual PL/SQL reserved-word set (the Go source's package-level
     * {@code ReservedWords} map was not part of the converted file - port it from the same
     * {@code plsql} Go package, e.g. a generated {@code plsql_reservedwords.go} or similar,
     * and fill this set with the same keyword strings, uppercase).
     */
    private static final Set<String> RESERVED_WORDS = Set.of();

    /**
     * Token đã lex gần nhất TRÊN default channel (bỏ qua token ở hidden channel như
     * whitespace/comment) - null nếu chưa lex token nào (đầu input).
     */
    private Token lastToken;

    /**
     * Cache lazy cho isReservedKeywords() - build 1 lần từ RESERVED_WORDS, KHÔNG phải build lại
     * mỗi lần gọi (mirror initReservedMap() ở bản Go, dùng lazy-init giống hệt).
     */
    private Set<String> reservedSet;

    protected PlSqlLexerBase(CharStream input) {
        super(input);
    }

    /**
     * Override nextToken() để luôn ghi nhớ token cuối cùng TRÊN DEFAULT_CHANNEL - dùng cho
     * isNewlineAtPos() bên dưới (một số quyết định lexing phụ thuộc "token trước có phải cuối
     * dòng không", cần biết token thật gần nhất, không tính whitespace/comment).
     */
    @Override
    public Token nextToken() {
        Token next = super.nextToken();
        if (next.getChannel() == Token.DEFAULT_CHANNEL) {
            lastToken = next;
        }
        return next;
    }

    /**
     * true nếu vị trí lookahead {@code pos} (tính từ ký tự hiện tại trong CharStream) là cuối
     * input hoặc ký tự xuống dòng - dùng bởi các lexer rule cần biết "có đang đứng cuối dòng
     * không" (vd một số token PL/SQL nhạy cảm với xuống dòng). Luôn trả true nếu chưa có
     * lastToken nào (coi như đầu input là "dòng mới").
     */
    public boolean isNewlineAtPos(int pos) {
        if (lastToken == null) {
            return true;
        }
        int la = getInputStream().LA(pos);
        return la == IntStream.EOF || la == '\n';
    }

    /**
     * true nếu tokenType này CÓ THỂ dùng làm 1 identifier - gồm 2 token identifier "thật"
     * (DELIMITED_ID dạng "identifier", REGULAR_ID không quote) VÀ toàn bộ các từ khoá
     * non-reserved của PL/SQL (Oracle cho phép rất nhiều "soft keyword" được dùng làm tên
     * cột/bảng/alias nếu ngữ cảnh không mơ hồ - đây chính là danh sách đó, port nguyên vẹn từ
     * bản Go, KHÔNG rút gọn hay lược bớt để giữ đúng hành vi).
     */
    public boolean isIdentifier(int tokenType) {
        if (tokenType == Token.EOF) {
            return false;
        }
        return switch (tokenType) {
            case PlSqlLexer.DELIMITED_ID, PlSqlLexer.REGULAR_ID -> true;
            case PlSqlLexer.ABORT, PlSqlLexer.ABS, PlSqlLexer.ACCESSED, PlSqlLexer.ACCESS, PlSqlLexer.ACCOUNT,
                 PlSqlLexer.ACOS,
                 PlSqlLexer.ACTIVATE, PlSqlLexer.ACTIVE_COMPONENT, PlSqlLexer.ACTIVE_FUNCTION, PlSqlLexer.ACTIVE_TAG,
                 PlSqlLexer.ADD_COLUMN, PlSqlLexer.ADD_GROUP,
                 PlSqlLexer.ADD_MONTHS, PlSqlLexer.ADD, PlSqlLexer.ADJ_DATE, PlSqlLexer.ADMINISTER,
                 PlSqlLexer.ADMINISTRATOR, PlSqlLexer.ADMIN,
                 PlSqlLexer.ADVISE, PlSqlLexer.ADVISOR, PlSqlLexer.AFTER, PlSqlLexer.ALIAS, PlSqlLexer.ALLOCATE,
                 PlSqlLexer.ALLOW,
                 PlSqlLexer.ALL_ROWS, PlSqlLexer.ALWAYS, PlSqlLexer.ANALYZE, PlSqlLexer.ANCILLARY, PlSqlLexer.AND_EQUAL,
                 PlSqlLexer.ANTIJOIN,
                 PlSqlLexer.ANYSCHEMA, PlSqlLexer.APPENDCHILDXML, PlSqlLexer.APPEND, PlSqlLexer.APPEND_VALUES,
                 PlSqlLexer.APPLY, PlSqlLexer.ARCHIVELOG,
                 PlSqlLexer.ARCHIVE, PlSqlLexer.ARRAY, PlSqlLexer.ASCII, PlSqlLexer.ASCIISTR, PlSqlLexer.ASIN,
                 PlSqlLexer.ASSEMBLY,
                 PlSqlLexer.ASSOCIATE, PlSqlLexer.ASYNCHRONOUS, PlSqlLexer.ASYNC, PlSqlLexer.ATAN2, PlSqlLexer.ATAN,
                 PlSqlLexer.AT,
                 PlSqlLexer.ATTRIBUTE, PlSqlLexer.ATTRIBUTES, PlSqlLexer.AUTHENTICATED, PlSqlLexer.AUTHENTICATION,
                 PlSqlLexer.AUTHID, PlSqlLexer.AUTHORIZATION,
                 PlSqlLexer.AUTOALLOCATE, PlSqlLexer.AUTOEXTEND, PlSqlLexer.AUTOMATIC, PlSqlLexer.AUTO,
                 PlSqlLexer.AVAILABILITY, PlSqlLexer.AVG,
                 PlSqlLexer.BACKUP, PlSqlLexer.BASICFILE, PlSqlLexer.BASIC, PlSqlLexer.BATCH, PlSqlLexer.BECOME,
                 PlSqlLexer.BEFORE,
                 PlSqlLexer.BEGIN, PlSqlLexer.BEGIN_OUTLINE_DATA, PlSqlLexer.BEHALF, PlSqlLexer.BFILE,
                 PlSqlLexer.BFILENAME, PlSqlLexer.BIGFILE,
                 PlSqlLexer.BINARY_DOUBLE_INFINITY, PlSqlLexer.BINARY_DOUBLE, PlSqlLexer.BINARY_DOUBLE_NAN,
                 PlSqlLexer.BINARY_FLOAT_INFINITY, PlSqlLexer.BINARY_FLOAT, PlSqlLexer.BINARY_FLOAT_NAN,
                 PlSqlLexer.BINARY, PlSqlLexer.BIND_AWARE, PlSqlLexer.BINDING, PlSqlLexer.BIN_TO_NUM, PlSqlLexer.BITAND,
                 PlSqlLexer.BITMAP,
                 PlSqlLexer.BITMAPS, PlSqlLexer.BITMAP_TREE, PlSqlLexer.BITS, PlSqlLexer.BLOB, PlSqlLexer.BLOCK,
                 PlSqlLexer.BLOCK_RANGE,
                 PlSqlLexer.BLOCKSIZE, PlSqlLexer.BLOCKS, PlSqlLexer.BODY, PlSqlLexer.BOTH, PlSqlLexer.BOUND,
                 PlSqlLexer.BRANCH,
                 PlSqlLexer.BREADTH, PlSqlLexer.BROADCAST, PlSqlLexer.BUFFER_CACHE, PlSqlLexer.BUFFER,
                 PlSqlLexer.BUFFER_POOL, PlSqlLexer.BUILD,
                 PlSqlLexer.BULK, PlSqlLexer.BYPASS_RECURSIVE_CHECK, PlSqlLexer.BYPASS_UJVC, PlSqlLexer.BYTE,
                 PlSqlLexer.CACHE_CB, PlSqlLexer.CACHE_INSTANCES,
                 PlSqlLexer.CACHE, PlSqlLexer.CACHE_TEMP_TABLE, PlSqlLexer.CALL, PlSqlLexer.CANCEL,
                 PlSqlLexer.CARDINALITY, PlSqlLexer.CASCADE,
                 PlSqlLexer.CASE, PlSqlLexer.CAST, PlSqlLexer.CATEGORY, PlSqlLexer.CEIL, PlSqlLexer.CELL_FLASH_CACHE,
                 PlSqlLexer.CERTIFICATE,
                 PlSqlLexer.CFILE, PlSqlLexer.CHAINED, PlSqlLexer.CHANGE_DUPKEY_ERROR_INDEX, PlSqlLexer.CHANGE,
                 PlSqlLexer.CHARACTER, PlSqlLexer.CHAR_CS,
                 PlSqlLexer.CHARTOROWID, PlSqlLexer.CHECK_ACL_REWRITE, PlSqlLexer.CHECKPOINT, PlSqlLexer.CHILD,
                 PlSqlLexer.CHOOSE, PlSqlLexer.CHR,
                 PlSqlLexer.CHUNK, PlSqlLexer.CLASS, PlSqlLexer.CLEAR, PlSqlLexer.CLOB, PlSqlLexer.CLONE,
                 PlSqlLexer.CLOSE_CACHED_OPEN_CURSORS,
                 PlSqlLexer.CLOSE, PlSqlLexer.CLUSTER_BY_ROWID, PlSqlLexer.CLUSTER_ID, PlSqlLexer.CLUSTERING_FACTOR,
                 PlSqlLexer.CLUSTER_PROBABILITY, PlSqlLexer.CLUSTER_SET,
                 PlSqlLexer.COALESCE, PlSqlLexer.COALESCE_SQ, PlSqlLexer.COARSE, PlSqlLexer.CO_AUTH_IND,
                 PlSqlLexer.COLD, PlSqlLexer.COLLECT,
                 PlSqlLexer.COLUMNAR, PlSqlLexer.COLUMN_AUTH_INDICATOR, PlSqlLexer.COLUMN, PlSqlLexer.COLUMNS,
                 PlSqlLexer.COLUMN_STATS, PlSqlLexer.COLUMN_VALUE,
                 PlSqlLexer.COMMENT, PlSqlLexer.COMMIT, PlSqlLexer.COMMITTED, PlSqlLexer.COMPACT,
                 PlSqlLexer.COMPATIBILITY, PlSqlLexer.COMPILE,
                 PlSqlLexer.COMPLETE, PlSqlLexer.COMPLIANCE, PlSqlLexer.COMPOSE, PlSqlLexer.COMPOSITE_LIMIT,
                 PlSqlLexer.COMPOSITE, PlSqlLexer.COMPOUND,
                 PlSqlLexer.COMPUTE, PlSqlLexer.CONCAT, PlSqlLexer.CONFIRM, PlSqlLexer.CONFORMING,
                 PlSqlLexer.CONNECT_BY_CB_WHR_ONLY, PlSqlLexer.CONNECT_BY_COMBINE_SW,
                 PlSqlLexer.CONNECT_BY_COST_BASED, PlSqlLexer.CONNECT_BY_ELIM_DUPS, PlSqlLexer.CONNECT_BY_FILTERING,
                 PlSqlLexer.CONNECT_BY_ISCYCLE, PlSqlLexer.CONNECT_BY_ISLEAF, PlSqlLexer.CONNECT_BY_ROOT,
                 PlSqlLexer.CONNECT_TIME, PlSqlLexer.CONSIDER, PlSqlLexer.CONSISTENT, PlSqlLexer.CONSTANT,
                 PlSqlLexer.CONST, PlSqlLexer.CONSTRAINT,
                 PlSqlLexer.CONSTRAINTS, PlSqlLexer.CONTAINER, PlSqlLexer.CONTENT, PlSqlLexer.CONTENTS,
                 PlSqlLexer.CONTEXT, PlSqlLexer.CONTINUE,
                 PlSqlLexer.CONTROLFILE, PlSqlLexer.CONVERT, PlSqlLexer.CORR_K, PlSqlLexer.CORR, PlSqlLexer.CORR_S,
                 PlSqlLexer.CORRUPTION,
                 PlSqlLexer.CORRUPT_XID_ALL, PlSqlLexer.CORRUPT_XID, PlSqlLexer.COSH, PlSqlLexer.COS, PlSqlLexer.COST,
                 PlSqlLexer.COST_XML_QUERY_REWRITE,
                 PlSqlLexer.COUNT, PlSqlLexer.COVAR_POP, PlSqlLexer.COVAR_SAMP, PlSqlLexer.CPU_COSTING,
                 PlSqlLexer.CPU_PER_CALL, PlSqlLexer.CPU_PER_SESSION,
                 PlSqlLexer.CRASH, PlSqlLexer.CREATE_STORED_OUTLINES, PlSqlLexer.CREATION, PlSqlLexer.CROSSEDITION,
                 PlSqlLexer.CROSS, PlSqlLexer.CSCONVERT,
                 PlSqlLexer.CUBE_GB, PlSqlLexer.CUBE, PlSqlLexer.CUME_DISTM, PlSqlLexer.CUME_DIST,
                 PlSqlLexer.CURRENT_DATE, PlSqlLexer.CURRENT,
                 PlSqlLexer.CURRENT_SCHEMA, PlSqlLexer.CURRENT_TIME, PlSqlLexer.CURRENT_TIMESTAMP,
                 PlSqlLexer.CURRENT_USER, PlSqlLexer.CURRENTV, PlSqlLexer.CURSOR,
                 PlSqlLexer.CURSOR_SHARING_EXACT, PlSqlLexer.CURSOR_SPECIFIC_SEGMENT, PlSqlLexer.CV, PlSqlLexer.CYCLE,
                 PlSqlLexer.DANGLING, PlSqlLexer.DATABASE,
                 PlSqlLexer.DATAFILE, PlSqlLexer.DATAFILES, PlSqlLexer.DATA, PlSqlLexer.DATAOBJNO,
                 PlSqlLexer.DATAOBJ_TO_PARTITION, PlSqlLexer.DATE_MODE,
                 PlSqlLexer.DAY, PlSqlLexer.DBA, PlSqlLexer.DBA_RECYCLEBIN, PlSqlLexer.DBMS_STATS,
                 PlSqlLexer.DB_ROLE_CHANGE, PlSqlLexer.DBTIMEZONE,
                 PlSqlLexer.DB_VERSION, PlSqlLexer.DDL, PlSqlLexer.DEALLOCATE, PlSqlLexer.DEBUGGER, PlSqlLexer.DEBUG,
                 PlSqlLexer.DECLARE,
                 PlSqlLexer.DEC, PlSqlLexer.DECOMPOSE, PlSqlLexer.DECREMENT, PlSqlLexer.DECR, PlSqlLexer.DECRYPT,
                 PlSqlLexer.DEDUPLICATE,
                 PlSqlLexer.DEFAULTS, PlSqlLexer.DEFERRABLE, PlSqlLexer.DEFERRED, PlSqlLexer.DEFINED,
                 PlSqlLexer.DEFINER, PlSqlLexer.DEGREE,
                 PlSqlLexer.DELAY, PlSqlLexer.DELETEXML, PlSqlLexer.DEMAND, PlSqlLexer.DENSE_RANKM,
                 PlSqlLexer.DENSE_RANK, PlSqlLexer.DEPENDENT,
                 PlSqlLexer.DEPTH, PlSqlLexer.DEQUEUE, PlSqlLexer.DEREF, PlSqlLexer.DEREF_NO_REWRITE,
                 PlSqlLexer.DETACHED, PlSqlLexer.DETERMINES,
                 PlSqlLexer.DICTIONARY, PlSqlLexer.DIMENSION, PlSqlLexer.DIRECT_LOAD, PlSqlLexer.DIRECTORY,
                 PlSqlLexer.DIRECT_PATH, PlSqlLexer.DISABLE,
                 PlSqlLexer.DISABLE_PRESET, PlSqlLexer.DISABLE_RPKE, PlSqlLexer.DISALLOW, PlSqlLexer.DISASSOCIATE,
                 PlSqlLexer.DISCONNECT, PlSqlLexer.DISKGROUP,
                 PlSqlLexer.DISK, PlSqlLexer.DISKS, PlSqlLexer.DISMOUNT, PlSqlLexer.DISTINGUISHED,
                 PlSqlLexer.DISTRIBUTED, PlSqlLexer.DML,
                 PlSqlLexer.DML_UPDATE, PlSqlLexer.DOCFIDELITY, PlSqlLexer.DOCUMENT, PlSqlLexer.DOMAIN_INDEX_FILTER,
                 PlSqlLexer.DOMAIN_INDEX_NO_SORT, PlSqlLexer.DOMAIN_INDEX_SORT,
                 PlSqlLexer.DOUBLE, PlSqlLexer.DOWNGRADE, PlSqlLexer.DRIVING_SITE, PlSqlLexer.DROP_COLUMN,
                 PlSqlLexer.DROP_GROUP, PlSqlLexer.DST_UPGRADE_INSERT_CONV,
                 PlSqlLexer.DUMP, PlSqlLexer.DYNAMIC, PlSqlLexer.DYNAMIC_SAMPLING_EST_CDN, PlSqlLexer.DYNAMIC_SAMPLING,
                 PlSqlLexer.EACH, PlSqlLexer.EDITIONING,
                 PlSqlLexer.EDITION, PlSqlLexer.EDITIONS, PlSqlLexer.ELEMENT, PlSqlLexer.ELIMINATE_JOIN,
                 PlSqlLexer.ELIMINATE_OBY, PlSqlLexer.ELIMINATE_OUTER_JOIN,
                 PlSqlLexer.EMPTY_BLOB, PlSqlLexer.EMPTY_CLOB, PlSqlLexer.EMPTY, PlSqlLexer.ENABLE,
                 PlSqlLexer.ENABLE_PRESET, PlSqlLexer.ENCODING,
                 PlSqlLexer.ENCRYPTION, PlSqlLexer.ENCRYPT, PlSqlLexer.END_OUTLINE_DATA, PlSqlLexer.ENFORCED,
                 PlSqlLexer.ENFORCE, PlSqlLexer.ENQUEUE,
                 PlSqlLexer.ENTERPRISE, PlSqlLexer.ENTITYESCAPING, PlSqlLexer.ENTRY, PlSqlLexer.ERROR_ARGUMENT,
                 PlSqlLexer.ERROR, PlSqlLexer.ERROR_ON_OVERLAP_TIME,
                 PlSqlLexer.ERRORS, PlSqlLexer.ESCAPE, PlSqlLexer.ESTIMATE, PlSqlLexer.EVALNAME, PlSqlLexer.EVALUATION,
                 PlSqlLexer.EVENTS,
                 PlSqlLexer.EVERY, PlSqlLexer.EXCEPTIONS, PlSqlLexer.EXCEPT, PlSqlLexer.EXCHANGE, PlSqlLexer.EXCLUDE,
                 PlSqlLexer.EXCLUDING,
                 PlSqlLexer.EXECUTE, PlSqlLexer.EXEMPT, PlSqlLexer.EXISTSNODE, PlSqlLexer.EXPAND_GSET_TO_UNION,
                 PlSqlLexer.EXPAND_TABLE, PlSqlLexer.EXPIRE,
                 PlSqlLexer.EXPLAIN, PlSqlLexer.EXPLOSION, PlSqlLexer.EXP, PlSqlLexer.EXPORT,
                 PlSqlLexer.EXPR_CORR_CHECK, PlSqlLexer.EXTENDS,
                 PlSqlLexer.EXTENT, PlSqlLexer.EXTENTS, PlSqlLexer.EXTERNALLY, PlSqlLexer.EXTERNAL, PlSqlLexer.EXTRACT,
                 PlSqlLexer.EXTRACTVALUE,
                 PlSqlLexer.EXTRA, PlSqlLexer.FACILITY, PlSqlLexer.FACT, PlSqlLexer.FACTORIZE_JOIN,
                 PlSqlLexer.FAILED_LOGIN_ATTEMPTS, PlSqlLexer.FAILED,
                 PlSqlLexer.FAILGROUP, PlSqlLexer.FALSE, PlSqlLexer.FAST, PlSqlLexer.FBTSCAN, PlSqlLexer.FEATURE_ID,
                 PlSqlLexer.FEATURE_SET,
                 PlSqlLexer.FEATURE_VALUE, PlSqlLexer.FILE, PlSqlLexer.FILESYSTEM_LIKE_LOGGING, PlSqlLexer.FILTER,
                 PlSqlLexer.FINAL, PlSqlLexer.FINE,
                 PlSqlLexer.FINISH, PlSqlLexer.FIRSTM, PlSqlLexer.FIRST, PlSqlLexer.FIRST_ROWS, PlSqlLexer.FIRST_VALUE,
                 PlSqlLexer.FLAGGER,
                 PlSqlLexer.FLASHBACK, PlSqlLexer.FLASH_CACHE, PlSqlLexer.FLOB, PlSqlLexer.FLOOR, PlSqlLexer.FLUSH,
                 PlSqlLexer.FOLDER,
                 PlSqlLexer.FOLLOWING, PlSqlLexer.FOLLOWS, PlSqlLexer.FORCE, PlSqlLexer.FORCE_XML_QUERY_REWRITE,
                 PlSqlLexer.FOREIGN, PlSqlLexer.FOREVER,
                 PlSqlLexer.FORWARD, PlSqlLexer.FRAGMENT_NUMBER, PlSqlLexer.FREELIST, PlSqlLexer.FREELISTS,
                 PlSqlLexer.FREEPOOLS, PlSqlLexer.FRESH,
                 PlSqlLexer.FROM_TZ, PlSqlLexer.FULL, PlSqlLexer.FULL_OUTER_JOIN_TO_OUTER, PlSqlLexer.FUNCTION,
                 PlSqlLexer.FUNCTIONS, PlSqlLexer.GATHER_PLAN_STATISTICS,
                 PlSqlLexer.GBY_CONC_ROLLUP, PlSqlLexer.GBY_PUSHDOWN, PlSqlLexer.GENERATED, PlSqlLexer.GLOBALLY,
                 PlSqlLexer.GLOBAL, PlSqlLexer.GLOBAL_NAME,
                 PlSqlLexer.GLOBAL_TOPIC_ENABLED, PlSqlLexer.GREATEST, PlSqlLexer.GROUP_BY, PlSqlLexer.GROUP_ID,
                 PlSqlLexer.GROUPING_ID, PlSqlLexer.GROUPING,
                 PlSqlLexer.GROUPS, PlSqlLexer.GUARANTEED, PlSqlLexer.GUARANTEE, PlSqlLexer.GUARD, PlSqlLexer.HASH_AJ,
                 PlSqlLexer.HASHKEYS,
                 PlSqlLexer.HASH, PlSqlLexer.HASH_SJ, PlSqlLexer.HEADER, PlSqlLexer.HEAP, PlSqlLexer.HELP,
                 PlSqlLexer.HEXTORAW,
                 PlSqlLexer.HEXTOREF, PlSqlLexer.HIDDEN_KEYWORD, PlSqlLexer.HIDE, PlSqlLexer.HIERARCHY, PlSqlLexer.HIGH,
                 PlSqlLexer.HINTSET_BEGIN,
                 PlSqlLexer.HINTSET_END, PlSqlLexer.HOT, PlSqlLexer.HOUR, PlSqlLexer.HWM_BROKERED, PlSqlLexer.HYBRID,
                 PlSqlLexer.IDENTIFIER,
                 PlSqlLexer.IDENTITY, PlSqlLexer.IDGENERATORS, PlSqlLexer.IDLE_TIME, PlSqlLexer.ID, PlSqlLexer.IF,
                 PlSqlLexer.IGNORE,
                 PlSqlLexer.IGNORE_OPTIM_EMBEDDED_HINTS, PlSqlLexer.IGNORE_ROW_ON_DUPKEY_INDEX,
                 PlSqlLexer.IGNORE_WHERE_CLAUSE, PlSqlLexer.IMMEDIATE, PlSqlLexer.IMPACT, PlSqlLexer.IMPORT,
                 PlSqlLexer.INCLUDE, PlSqlLexer.INCLUDE_VERSION, PlSqlLexer.INCLUDING, PlSqlLexer.INCREMENTAL,
                 PlSqlLexer.INCREMENT, PlSqlLexer.INCR,
                 PlSqlLexer.INDENT, PlSqlLexer.INDEX_ASC, PlSqlLexer.INDEX_COMBINE, PlSqlLexer.INDEX_DESC,
                 PlSqlLexer.INDEXED, PlSqlLexer.INDEXES,
                 PlSqlLexer.INDEX_FFS, PlSqlLexer.INDEX_FILTER, PlSqlLexer.INDEX_JOIN, PlSqlLexer.INDEX_ROWS,
                 PlSqlLexer.INDEX_RRS, PlSqlLexer.INDEX_RS_ASC,
                 PlSqlLexer.INDEX_RS_DESC, PlSqlLexer.INDEX_RS, PlSqlLexer.INDEX_SCAN, PlSqlLexer.INDEX_SKIP_SCAN,
                 PlSqlLexer.INDEX_SS_ASC, PlSqlLexer.INDEX_SS_DESC,
                 PlSqlLexer.INDEX_SS, PlSqlLexer.INDEX_STATS, PlSqlLexer.INDEXTYPE, PlSqlLexer.INDEXTYPES,
                 PlSqlLexer.INDICATOR, PlSqlLexer.INFINITE,
                 PlSqlLexer.INFORMATIONAL, PlSqlLexer.INITCAP, PlSqlLexer.INITIALIZED, PlSqlLexer.INITIALLY,
                 PlSqlLexer.INITIAL, PlSqlLexer.INITRANS,
                 PlSqlLexer.INLINE, PlSqlLexer.INLINE_XMLTYPE_NT, PlSqlLexer.IN_MEMORY_METADATA, PlSqlLexer.INNER,
                 PlSqlLexer.INSERTCHILDXMLAFTER, PlSqlLexer.INSERTCHILDXMLBEFORE,
                 PlSqlLexer.INSERTCHILDXML, PlSqlLexer.INSERTXMLAFTER, PlSqlLexer.INSERTXMLBEFORE, PlSqlLexer.INSTANCE,
                 PlSqlLexer.INSTANCES, PlSqlLexer.INSTANTIABLE,
                 PlSqlLexer.INSTANTLY, PlSqlLexer.INSTEAD, PlSqlLexer.INSTR2, PlSqlLexer.INSTR4, PlSqlLexer.INSTRB,
                 PlSqlLexer.INSTRC,
                 PlSqlLexer.INSTR, PlSqlLexer.INTERMEDIATE, PlSqlLexer.INTERNAL_CONVERT, PlSqlLexer.INTERNAL_USE,
                 PlSqlLexer.INTERPRETED, PlSqlLexer.INTERVAL,
                 PlSqlLexer.INT, PlSqlLexer.INVALIDATE, PlSqlLexer.INVISIBLE, PlSqlLexer.IN_XQUERY,
                 PlSqlLexer.ISOLATION_LEVEL, PlSqlLexer.ISOLATION,
                 PlSqlLexer.ITERATE, PlSqlLexer.ITERATION_NUMBER, PlSqlLexer.JAVA, PlSqlLexer.JOB, PlSqlLexer.JOIN,
                 PlSqlLexer.KEEP_DUPLICATES,
                 PlSqlLexer.KEEP, PlSqlLexer.KERBEROS, PlSqlLexer.KEY_LENGTH, PlSqlLexer.KEY, PlSqlLexer.KEYSIZE,
                 PlSqlLexer.KEYS,
                 PlSqlLexer.KILL, PlSqlLexer.LAG, PlSqlLexer.LAST_DAY, PlSqlLexer.LAST, PlSqlLexer.LAST_VALUE,
                 PlSqlLexer.LATERAL,
                 PlSqlLexer.LAYER, PlSqlLexer.LDAP_REGISTRATION_ENABLED, PlSqlLexer.LDAP_REGISTRATION,
                 PlSqlLexer.LDAP_REG_SYNC_INTERVAL, PlSqlLexer.LEADING, PlSqlLexer.LEAD,
                 PlSqlLexer.LEAF, PlSqlLexer.LEAST, PlSqlLexer.LEFT, PlSqlLexer.LENGTH2, PlSqlLexer.LENGTH4,
                 PlSqlLexer.LENGTHB,
                 PlSqlLexer.LENGTHC, PlSqlLexer.LENGTH, PlSqlLexer.LESS, PlSqlLexer.LEVEL, PlSqlLexer.LEVELS,
                 PlSqlLexer.LIBRARY,
                 PlSqlLexer.LIFE, PlSqlLexer.LIFETIME, PlSqlLexer.LIKE2, PlSqlLexer.LIKE4, PlSqlLexer.LIKEC,
                 PlSqlLexer.LIKE_EXPAND,
                 PlSqlLexer.LIMIT, PlSqlLexer.LINK, PlSqlLexer.LISTAGG, PlSqlLexer.LIST, PlSqlLexer.LN,
                 PlSqlLexer.LNNVL,
                 PlSqlLexer.LOAD, PlSqlLexer.LOB, PlSqlLexer.LOBNVL, PlSqlLexer.LOBS, PlSqlLexer.LOCAL_INDEXES,
                 PlSqlLexer.LOCAL,
                 PlSqlLexer.LOCALTIME, PlSqlLexer.LOCALTIMESTAMP, PlSqlLexer.LOCATION, PlSqlLexer.LOCATOR,
                 PlSqlLexer.LOCKED, PlSqlLexer.LOGFILE,
                 PlSqlLexer.LOGFILES, PlSqlLexer.LOGGING, PlSqlLexer.LOGICAL, PlSqlLexer.LOGICAL_READS_PER_CALL,
                 PlSqlLexer.LOGICAL_READS_PER_SESSION, PlSqlLexer.LOG,
                 PlSqlLexer.LOGOFF, PlSqlLexer.LOGON, PlSqlLexer.LOG_READ_ONLY_VIOLATIONS, PlSqlLexer.LOWER,
                 PlSqlLexer.LOW, PlSqlLexer.LPAD,
                 PlSqlLexer.LTRIM, PlSqlLexer.MAIN, PlSqlLexer.MAKE_REF, PlSqlLexer.MANAGED, PlSqlLexer.MANAGEMENT,
                 PlSqlLexer.MANAGE,
                 PlSqlLexer.MANAGER, PlSqlLexer.MANUAL, PlSqlLexer.MAPPING, PlSqlLexer.MASTER, PlSqlLexer.MATCHED,
                 PlSqlLexer.MATERIALIZED,
                 PlSqlLexer.MATERIALIZE, PlSqlLexer.MAXARCHLOGS, PlSqlLexer.MAXDATAFILES, PlSqlLexer.MAXEXTENTS,
                 PlSqlLexer.MAXIMIZE, PlSqlLexer.MAXINSTANCES,
                 PlSqlLexer.MAXLOGFILES, PlSqlLexer.MAXLOGHISTORY, PlSqlLexer.MAXLOGMEMBERS, PlSqlLexer.MAX,
                 PlSqlLexer.MAXSIZE, PlSqlLexer.MAXTRANS,
                 PlSqlLexer.MAXVALUE, PlSqlLexer.MEASURE, PlSqlLexer.MEASURES, PlSqlLexer.MEDIAN, PlSqlLexer.MEDIUM,
                 PlSqlLexer.MEMBER,
                 PlSqlLexer.MEMOPTIMIZE, PlSqlLexer.MEMORY, PlSqlLexer.MERGEACTIONS, PlSqlLexer.MERGE_AJ,
                 PlSqlLexer.MERGE_CONST_ON, PlSqlLexer.MERGE,
                 PlSqlLexer.MERGE_SJ, PlSqlLexer.METHOD, PlSqlLexer.MIGRATE, PlSqlLexer.MIGRATION,
                 PlSqlLexer.MINEXTENTS, PlSqlLexer.MINIMIZE,
                 PlSqlLexer.MINIMUM, PlSqlLexer.MINING, PlSqlLexer.MIN, PlSqlLexer.MINUS_NULL, PlSqlLexer.MINUTE,
                 PlSqlLexer.MINVALUE,
                 PlSqlLexer.MIRRORCOLD, PlSqlLexer.MIRRORHOT, PlSqlLexer.MIRROR, PlSqlLexer.MLSLABEL,
                 PlSqlLexer.MODEL_COMPILE_SUBQUERY, PlSqlLexer.MODEL_DONTVERIFY_UNIQUENESS,
                 PlSqlLexer.MODEL_DYNAMIC_SUBQUERY, PlSqlLexer.MODEL_MIN_ANALYSIS, PlSqlLexer.MODEL,
                 PlSqlLexer.MODEL_NO_ANALYSIS, PlSqlLexer.MODEL_PBY, PlSqlLexer.MODEL_PUSH_REF,
                 PlSqlLexer.MODIFY_COLUMN_TYPE, PlSqlLexer.MODIFY, PlSqlLexer.MOD, PlSqlLexer.MONITORING,
                 PlSqlLexer.MONITOR, PlSqlLexer.MONTH,
                 PlSqlLexer.MONTHS_BETWEEN, PlSqlLexer.MOUNT, PlSqlLexer.MOUNTPATH, PlSqlLexer.MOVEMENT,
                 PlSqlLexer.MOVE, PlSqlLexer.MULTISET,
                 PlSqlLexer.MV_MERGE, PlSqlLexer.NAMED, PlSqlLexer.NAME, PlSqlLexer.NAMESPACE, PlSqlLexer.NAN,
                 PlSqlLexer.NANVL,
                 PlSqlLexer.NATIONAL, PlSqlLexer.NATIVE_FULL_OUTER_JOIN, PlSqlLexer.NATIVE, PlSqlLexer.NATURAL,
                 PlSqlLexer.NAV, PlSqlLexer.NCHAR_CS,
                 PlSqlLexer.NCHAR, PlSqlLexer.NCHR, PlSqlLexer.NCLOB, PlSqlLexer.NEEDED, PlSqlLexer.NESTED,
                 PlSqlLexer.NESTED_TABLE_FAST_INSERT,
                 PlSqlLexer.NESTED_TABLE_GET_REFS, PlSqlLexer.NESTED_TABLE_ID, PlSqlLexer.NESTED_TABLE_SET_REFS,
                 PlSqlLexer.NESTED_TABLE_SET_SETID, PlSqlLexer.NETWORK, PlSqlLexer.NEVER,
                 PlSqlLexer.NEW, PlSqlLexer.NEW_TIME, PlSqlLexer.NEXT_DAY, PlSqlLexer.NEXT, PlSqlLexer.NL_AJ,
                 PlSqlLexer.NLJ_BATCHING,
                 PlSqlLexer.NLJ_INDEX_FILTER, PlSqlLexer.NLJ_INDEX_SCAN, PlSqlLexer.NLJ_PREFETCH,
                 PlSqlLexer.NLS_CALENDAR, PlSqlLexer.NLS_CHARACTERSET, PlSqlLexer.NLS_CHARSET_DECL_LEN,
                 PlSqlLexer.NLS_CHARSET_ID, PlSqlLexer.NLS_CHARSET_NAME, PlSqlLexer.NLS_COMP, PlSqlLexer.NLS_CURRENCY,
                 PlSqlLexer.NLS_DATE_FORMAT, PlSqlLexer.NLS_DATE_LANGUAGE,
                 PlSqlLexer.NLS_INITCAP, PlSqlLexer.NLS_ISO_CURRENCY, PlSqlLexer.NL_SJ, PlSqlLexer.NLS_LANG,
                 PlSqlLexer.NLS_LANGUAGE, PlSqlLexer.NLS_LENGTH_SEMANTICS,
                 PlSqlLexer.NLS_LOWER, PlSqlLexer.NLS_NCHAR_CONV_EXCP, PlSqlLexer.NLS_NUMERIC_CHARACTERS,
                 PlSqlLexer.NLS_SORT, PlSqlLexer.NLSSORT, PlSqlLexer.NLS_SPECIAL_CHARS,
                 PlSqlLexer.NLS_TERRITORY, PlSqlLexer.NLS_UPPER, PlSqlLexer.NO_ACCESS, PlSqlLexer.NOAPPEND,
                 PlSqlLexer.NOARCHIVELOG, PlSqlLexer.NOAUDIT,
                 PlSqlLexer.NO_BASETABLE_MULTIMV_REWRITE, PlSqlLexer.NO_BIND_AWARE, PlSqlLexer.NO_BUFFER,
                 PlSqlLexer.NOCACHE, PlSqlLexer.NO_CARTESIAN, PlSqlLexer.NO_CHECK_ACL_REWRITE,
                 PlSqlLexer.NO_CLUSTER_BY_ROWID, PlSqlLexer.NO_COALESCE_SQ, PlSqlLexer.NO_CONNECT_BY_CB_WHR_ONLY,
                 PlSqlLexer.NO_CONNECT_BY_COMBINE_SW, PlSqlLexer.NO_CONNECT_BY_COST_BASED,
                 PlSqlLexer.NO_CONNECT_BY_ELIM_DUPS,
                 PlSqlLexer.NO_CONNECT_BY_FILTERING, PlSqlLexer.NO_COST_XML_QUERY_REWRITE, PlSqlLexer.NO_CPU_COSTING,
                 PlSqlLexer.NOCPU_COSTING, PlSqlLexer.NOCYCLE, PlSqlLexer.NODELAY,
                 PlSqlLexer.NO_DOMAIN_INDEX_FILTER, PlSqlLexer.NO_DST_UPGRADE_INSERT_CONV, PlSqlLexer.NO_ELIMINATE_JOIN,
                 PlSqlLexer.NO_ELIMINATE_OBY, PlSqlLexer.NO_ELIMINATE_OUTER_JOIN, PlSqlLexer.NOENTITYESCAPING,
                 PlSqlLexer.NO_EXPAND_GSET_TO_UNION, PlSqlLexer.NO_EXPAND, PlSqlLexer.NO_EXPAND_TABLE,
                 PlSqlLexer.NO_FACT, PlSqlLexer.NO_FACTORIZE_JOIN, PlSqlLexer.NO_FILTERING,
                 PlSqlLexer.NOFORCE, PlSqlLexer.NO_FULL_OUTER_JOIN_TO_OUTER, PlSqlLexer.NO_GBY_PUSHDOWN,
                 PlSqlLexer.NOGUARANTEE, PlSqlLexer.NO_INDEX_FFS, PlSqlLexer.NO_INDEX,
                 PlSqlLexer.NO_INDEX_SS, PlSqlLexer.NO_LOAD, PlSqlLexer.NOLOCAL, PlSqlLexer.NOLOGGING,
                 PlSqlLexer.NOMAPPING, PlSqlLexer.NOMAXVALUE,
                 PlSqlLexer.NO_MERGE, PlSqlLexer.NOMINIMIZE, PlSqlLexer.NOMINVALUE, PlSqlLexer.NO_MODEL_PUSH_REF,
                 PlSqlLexer.NO_MONITORING, PlSqlLexer.NOMONITORING,
                 PlSqlLexer.NO_MONITOR, PlSqlLexer.NO_MULTIMV_REWRITE, PlSqlLexer.NO,
                 PlSqlLexer.NO_NATIVE_FULL_OUTER_JOIN, PlSqlLexer.NONBLOCKING, PlSqlLexer.NONE,
                 PlSqlLexer.NO_NLJ_BATCHING, PlSqlLexer.NO_NLJ_PREFETCH, PlSqlLexer.NONSCHEMA, PlSqlLexer.NOORDER,
                 PlSqlLexer.NO_ORDER_ROLLUPS, PlSqlLexer.NO_OUTER_JOIN_TO_ANTI,
                 PlSqlLexer.NO_OUTER_JOIN_TO_INNER, PlSqlLexer.NOOVERRIDE, PlSqlLexer.NO_PARALLEL_INDEX,
                 PlSqlLexer.NOPARALLEL_INDEX, PlSqlLexer.NO_PARALLEL, PlSqlLexer.NOPARALLEL,
                 PlSqlLexer.NO_PARTIAL_COMMIT, PlSqlLexer.NO_PLACE_DISTINCT, PlSqlLexer.NO_PLACE_GROUP_BY,
                 PlSqlLexer.NO_PQ_MAP, PlSqlLexer.NO_PRUNE_GSETS, PlSqlLexer.NO_PULL_PRED,
                 PlSqlLexer.NO_PUSH_PRED, PlSqlLexer.NO_PUSH_SUBQ, PlSqlLexer.NO_PX_JOIN_FILTER, PlSqlLexer.NO_QKN_BUFF,
                 PlSqlLexer.NO_QUERY_TRANSFORMATION, PlSqlLexer.NO_REF_CASCADE,
                 PlSqlLexer.NORELY, PlSqlLexer.NOREPAIR, PlSqlLexer.NORESETLOGS, PlSqlLexer.NO_RESULT_CACHE,
                 PlSqlLexer.NOREVERSE, PlSqlLexer.NO_REWRITE,
                 PlSqlLexer.NOREWRITE, PlSqlLexer.NORMAL, PlSqlLexer.NOROWDEPENDENCIES, PlSqlLexer.NOSCHEMACHECK,
                 PlSqlLexer.NOSEGMENT, PlSqlLexer.NO_SEMIJOIN,
                 PlSqlLexer.NO_SEMI_TO_INNER, PlSqlLexer.NO_SET_TO_JOIN, PlSqlLexer.NOSORT, PlSqlLexer.NO_SQL_TUNE,
                 PlSqlLexer.NO_STAR_TRANSFORMATION, PlSqlLexer.NO_STATEMENT_QUEUING,
                 PlSqlLexer.NO_STATS_GSETS, PlSqlLexer.NOSTRICT, PlSqlLexer.NO_SUBQUERY_PRUNING,
                 PlSqlLexer.NO_SUBSTRB_PAD, PlSqlLexer.NO_SWAP_JOIN_INPUTS, PlSqlLexer.NOSWITCH,
                 PlSqlLexer.NO_TABLE_LOOKUP_BY_NL, PlSqlLexer.NO_TEMP_TABLE, PlSqlLexer.NOTHING,
                 PlSqlLexer.NOTIFICATION, PlSqlLexer.NO_TRANSFORM_DISTINCT_AGG, PlSqlLexer.NO_UNNEST,
                 PlSqlLexer.NO_USE_HASH_AGGREGATION, PlSqlLexer.NO_USE_HASH_GBY_FOR_PUSHDOWN, PlSqlLexer.NO_USE_HASH,
                 PlSqlLexer.NO_USE_INVISIBLE_INDEXES, PlSqlLexer.NO_USE_MERGE, PlSqlLexer.NO_USE_NL,
                 PlSqlLexer.NOVALIDATE, PlSqlLexer.NO_XDB_FASTPATH_INSERT, PlSqlLexer.NO_XML_DML_REWRITE,
                 PlSqlLexer.NO_XMLINDEX_REWRITE_IN_SELECT, PlSqlLexer.NO_XMLINDEX_REWRITE,
                 PlSqlLexer.NO_XML_QUERY_REWRITE,
                 PlSqlLexer.NTH_VALUE, PlSqlLexer.NTILE, PlSqlLexer.NULLIF, PlSqlLexer.NULLS, PlSqlLexer.NUMERIC,
                 PlSqlLexer.NUM_INDEX_KEYS,
                 PlSqlLexer.NUMTODSINTERVAL, PlSqlLexer.NUMTOYMINTERVAL, PlSqlLexer.NVARCHAR2, PlSqlLexer.NVL2,
                 PlSqlLexer.NVL, PlSqlLexer.OBJECT2XML,
                 PlSqlLexer.OBJECT, PlSqlLexer.OBJNO, PlSqlLexer.OBJNO_REUSE, PlSqlLexer.OCCURENCES, PlSqlLexer.OFFLINE,
                 PlSqlLexer.OFF,
                 PlSqlLexer.OIDINDEX, PlSqlLexer.OID, PlSqlLexer.OLAP, PlSqlLexer.OLD, PlSqlLexer.OLD_PUSH_PRED,
                 PlSqlLexer.OLTP,
                 PlSqlLexer.ONLINE, PlSqlLexer.ONLY, PlSqlLexer.OPAQUE, PlSqlLexer.OPAQUE_TRANSFORM,
                 PlSqlLexer.OPAQUE_XCANONICAL, PlSqlLexer.OPCODE,
                 PlSqlLexer.OPEN, PlSqlLexer.OPERATIONS, PlSqlLexer.OPERATOR, PlSqlLexer.OPT_ESTIMATE,
                 PlSqlLexer.OPTIMAL, PlSqlLexer.OPTIMIZE,
                 PlSqlLexer.OPTIMIZER_FEATURES_ENABLE, PlSqlLexer.OPTIMIZER_GOAL, PlSqlLexer.OPT_PARAM,
                 PlSqlLexer.ORA_BRANCH, PlSqlLexer.ORADEBUG, PlSqlLexer.ORA_DST_AFFECTED,
                 PlSqlLexer.ORA_DST_CONVERT, PlSqlLexer.ORA_DST_ERROR, PlSqlLexer.ORA_GET_ACLIDS,
                 PlSqlLexer.ORA_GET_PRIVILEGES, PlSqlLexer.ORA_HASH, PlSqlLexer.ORA_ROWSCN,
                 PlSqlLexer.ORA_ROWSCN_RAW, PlSqlLexer.ORA_ROWVERSION, PlSqlLexer.ORA_TABVERSION, PlSqlLexer.ORDERED,
                 PlSqlLexer.ORDERED_PREDICATES, PlSqlLexer.ORDINALITY,
                 PlSqlLexer.OR_EXPAND, PlSqlLexer.ORGANIZATION, PlSqlLexer.OR_PREDICATES, PlSqlLexer.OTHER,
                 PlSqlLexer.OUTER_JOIN_TO_ANTI, PlSqlLexer.OUTER_JOIN_TO_INNER,
                 PlSqlLexer.OUTER, PlSqlLexer.OUTLINE_LEAF, PlSqlLexer.OUTLINE, PlSqlLexer.OUT_OF_LINE,
                 PlSqlLexer.OVERFLOW, PlSqlLexer.OVERFLOW_NOMOVE,
                 PlSqlLexer.OVERLAPS, PlSqlLexer.OVER, PlSqlLexer.OWNER, PlSqlLexer.OWNERSHIP, PlSqlLexer.OWN,
                 PlSqlLexer.PACKAGE,
                 PlSqlLexer.PACKAGES, PlSqlLexer.PARALLEL_INDEX, PlSqlLexer.PARALLEL, PlSqlLexer.PARAMETERS,
                 PlSqlLexer.PARAM, PlSqlLexer.PARENT,
                 PlSqlLexer.PARITY, PlSqlLexer.PARTIALLY, PlSqlLexer.PARTITION_HASH, PlSqlLexer.PARTITION_LIST,
                 PlSqlLexer.PARTITION, PlSqlLexer.PARTITION_RANGE,
                 PlSqlLexer.PARTITIONS, PlSqlLexer.PARTNUMINST, PlSqlLexer.PASSING, PlSqlLexer.PASSWORD_GRACE_TIME,
                 PlSqlLexer.PASSWORD_LIFE_TIME, PlSqlLexer.PASSWORD_LOCK_TIME,
                 PlSqlLexer.PASSWORD, PlSqlLexer.PASSWORD_REUSE_MAX, PlSqlLexer.PASSWORD_REUSE_TIME,
                 PlSqlLexer.PASSWORD_VERIFY_FUNCTION, PlSqlLexer.PATH, PlSqlLexer.PATHS,
                 PlSqlLexer.PBL_HS_BEGIN, PlSqlLexer.PBL_HS_END, PlSqlLexer.PCTINCREASE, PlSqlLexer.PCTTHRESHOLD,
                 PlSqlLexer.PCTUSED, PlSqlLexer.PCTVERSION,
                 PlSqlLexer.PENDING, PlSqlLexer.PERCENTILE_CONT, PlSqlLexer.PERCENTILE_DISC, PlSqlLexer.PERCENT_KEYWORD,
                 PlSqlLexer.PERCENT_RANKM, PlSqlLexer.PERCENT_RANK,
                 PlSqlLexer.PERFORMANCE, PlSqlLexer.PERMANENT, PlSqlLexer.PERMISSION, PlSqlLexer.PFILE,
                 PlSqlLexer.PHYSICAL, PlSqlLexer.PIKEY,
                 PlSqlLexer.PIV_GB, PlSqlLexer.PIVOT, PlSqlLexer.PIV_SSF, PlSqlLexer.PLACE_DISTINCT,
                 PlSqlLexer.PLACE_GROUP_BY, PlSqlLexer.PLAN,
                 PlSqlLexer.PLSCOPE_SETTINGS, PlSqlLexer.PLSQL_CCFLAGS, PlSqlLexer.PLSQL_CODE_TYPE,
                 PlSqlLexer.PLSQL_DEBUG, PlSqlLexer.PLSQL_OPTIMIZE_LEVEL, PlSqlLexer.PLSQL_WARNINGS,
                 PlSqlLexer.POINT, PlSqlLexer.POLICY, PlSqlLexer.POST_TRANSACTION,
                 PlSqlLexer.POWERMULTISET_BY_CARDINALITY, PlSqlLexer.POWERMULTISET, PlSqlLexer.POWER,
                 PlSqlLexer.PQ_DISTRIBUTE, PlSqlLexer.PQ_MAP, PlSqlLexer.PQ_NOMAP, PlSqlLexer.PREBUILT,
                 PlSqlLexer.PRECEDES, PlSqlLexer.PRECEDING,
                 PlSqlLexer.PRECISION, PlSqlLexer.PRECOMPUTE_SUBQUERY, PlSqlLexer.PREDICATE_REORDERS,
                 PlSqlLexer.PREDICTION_BOUNDS, PlSqlLexer.PREDICTION_COST, PlSqlLexer.PREDICTION_DETAILS,
                 PlSqlLexer.PREDICTION, PlSqlLexer.PREDICTION_PROBABILITY, PlSqlLexer.PREDICTION_SET,
                 PlSqlLexer.PREPARE, PlSqlLexer.PRESENT, PlSqlLexer.PRESENTNNV,
                 PlSqlLexer.PRESENTV, PlSqlLexer.PRESERVE, PlSqlLexer.PRESERVE_OID, PlSqlLexer.PREVIOUS,
                 PlSqlLexer.PRIMARY, PlSqlLexer.PRIVATE,
                 PlSqlLexer.PRIVATE_SGA, PlSqlLexer.PRIVILEGE, PlSqlLexer.PRIVILEGES, PlSqlLexer.PROCEDURAL,
                 PlSqlLexer.PROCEDURE, PlSqlLexer.PROCESS,
                 PlSqlLexer.PROFILE, PlSqlLexer.PROGRAM, PlSqlLexer.PROJECT, PlSqlLexer.PROPAGATE, PlSqlLexer.PROTECTED,
                 PlSqlLexer.PROTECTION,
                 PlSqlLexer.PULL_PRED, PlSqlLexer.PURGE, PlSqlLexer.PUSH_PRED, PlSqlLexer.PUSH_SUBQ,
                 PlSqlLexer.PX_GRANULE, PlSqlLexer.PX_JOIN_FILTER,
                 PlSqlLexer.QB_NAME, PlSqlLexer.QUERY_BLOCK, PlSqlLexer.QUERY, PlSqlLexer.QUEUE_CURR, PlSqlLexer.QUEUE,
                 PlSqlLexer.QUEUE_ROWP,
                 PlSqlLexer.QUIESCE, PlSqlLexer.QUORUM, PlSqlLexer.QUOTA, PlSqlLexer.RANDOM_LOCAL, PlSqlLexer.RANDOM,
                 PlSqlLexer.RANGE,
                 PlSqlLexer.RANKM, PlSqlLexer.RANK, PlSqlLexer.RAPIDLY, PlSqlLexer.RATIO_TO_REPORT, PlSqlLexer.RAWTOHEX,
                 PlSqlLexer.RAWTONHEX,
                 PlSqlLexer.RBA, PlSqlLexer.RBO_OUTLINE, PlSqlLexer.RDBA, PlSqlLexer.READ, PlSqlLexer.READS,
                 PlSqlLexer.REAL,
                 PlSqlLexer.REBALANCE, PlSqlLexer.REBUILD, PlSqlLexer.RECORDS_PER_BLOCK, PlSqlLexer.RECOVERABLE,
                 PlSqlLexer.RECOVER, PlSqlLexer.RECOVERY,
                 PlSqlLexer.RECYCLEBIN, PlSqlLexer.RECYCLE, PlSqlLexer.REDACTION, PlSqlLexer.REDO, PlSqlLexer.REDUCED,
                 PlSqlLexer.REDUNDANCY,
                 PlSqlLexer.REF_CASCADE_CURSOR, PlSqlLexer.REFERENCED, PlSqlLexer.REFERENCE, PlSqlLexer.REFERENCES,
                 PlSqlLexer.REFERENCING, PlSqlLexer.REF,
                 PlSqlLexer.REFRESH, PlSqlLexer.REFTOHEX, PlSqlLexer.REGEXP_COUNT, PlSqlLexer.REGEXP_INSTR,
                 PlSqlLexer.REGEXP_LIKE, PlSqlLexer.REGEXP_REPLACE,
                 PlSqlLexer.REGEXP_SUBSTR, PlSqlLexer.REGISTER, PlSqlLexer.REGR_AVGX, PlSqlLexer.REGR_AVGY,
                 PlSqlLexer.REGR_COUNT, PlSqlLexer.REGR_INTERCEPT,
                 PlSqlLexer.REGR_R2, PlSqlLexer.REGR_SLOPE, PlSqlLexer.REGR_SXX, PlSqlLexer.REGR_SXY,
                 PlSqlLexer.REGR_SYY, PlSqlLexer.REGULAR,
                 PlSqlLexer.REJECT, PlSqlLexer.REKEY, PlSqlLexer.RELATIONAL, PlSqlLexer.RELY, PlSqlLexer.REMAINDER,
                 PlSqlLexer.REMOTE_MAPPED,
                 PlSqlLexer.REMOVE, PlSqlLexer.REPAIR, PlSqlLexer.REPEAT, PlSqlLexer.REPLACE, PlSqlLexer.REPLICATION,
                 PlSqlLexer.REQUIRED,
                 PlSqlLexer.RESETLOGS, PlSqlLexer.RESET, PlSqlLexer.RESIZE, PlSqlLexer.RESOLVE, PlSqlLexer.RESOLVER,
                 PlSqlLexer.RESPECT,
                 PlSqlLexer.RESTORE_AS_INTERVALS, PlSqlLexer.RESTORE, PlSqlLexer.RESTRICT_ALL_REF_CONS,
                 PlSqlLexer.RESTRICTED, PlSqlLexer.RESTRICT, PlSqlLexer.RESULT_CACHE,
                 PlSqlLexer.RESUMABLE, PlSqlLexer.RESUME, PlSqlLexer.RETENTION, PlSqlLexer.RETRY_ON_ROW_CHANGE,
                 PlSqlLexer.RETURNING, PlSqlLexer.RETURN,
                 PlSqlLexer.REUSE, PlSqlLexer.REVERSE, PlSqlLexer.REWRITE, PlSqlLexer.REWRITE_OR_ERROR,
                 PlSqlLexer.RIGHT, PlSqlLexer.ROLE,
                 PlSqlLexer.ROLES, PlSqlLexer.ROLLBACK, PlSqlLexer.ROLLING, PlSqlLexer.ROLLUP, PlSqlLexer.ROOT,
                 PlSqlLexer.ROUND,
                 PlSqlLexer.ROWDEPENDENCIES, PlSqlLexer.ROWID, PlSqlLexer.ROWIDTOCHAR, PlSqlLexer.ROWIDTONCHAR,
                 PlSqlLexer.ROW_LENGTH, PlSqlLexer.ROW,
                 PlSqlLexer.ROW_NUMBER, PlSqlLexer.ROWNUM, PlSqlLexer.ROWS, PlSqlLexer.RPAD, PlSqlLexer.RTRIM,
                 PlSqlLexer.RULE,
                 PlSqlLexer.RULES, PlSqlLexer.SALT, PlSqlLexer.SAMPLE, PlSqlLexer.SAVE_AS_INTERVALS,
                 PlSqlLexer.SAVEPOINT, PlSqlLexer.SB4,
                 PlSqlLexer.SCALE, PlSqlLexer.SCALE_ROWS, PlSqlLexer.SCAN_INSTANCES, PlSqlLexer.SCAN,
                 PlSqlLexer.SCHEDULER, PlSqlLexer.SCHEMACHECK,
                 PlSqlLexer.SCHEMA, PlSqlLexer.SCN_ASCENDING, PlSqlLexer.SCN, PlSqlLexer.SCOPE, PlSqlLexer.SD_ALL,
                 PlSqlLexer.SD_INHIBIT,
                 PlSqlLexer.SD_SHOW, PlSqlLexer.SEARCH, PlSqlLexer.SECOND, PlSqlLexer.SECUREFILE_DBA,
                 PlSqlLexer.SECUREFILE, PlSqlLexer.SECURITY,
                 PlSqlLexer.SEED, PlSqlLexer.SEG_BLOCK, PlSqlLexer.SEG_FILE, PlSqlLexer.SEGMENT, PlSqlLexer.SELECTIVITY,
                 PlSqlLexer.SEMIJOIN_DRIVER,
                 PlSqlLexer.SEMIJOIN, PlSqlLexer.SEMI_TO_INNER, PlSqlLexer.SEQUENCED, PlSqlLexer.SEQUENCE,
                 PlSqlLexer.SEQUENTIAL, PlSqlLexer.SERIALIZABLE,
                 PlSqlLexer.SERVERERROR, PlSqlLexer.SERVICE, PlSqlLexer.SESSION_CACHED_CURSORS, PlSqlLexer.SESSION,
                 PlSqlLexer.SESSIONS_PER_USER, PlSqlLexer.SESSIONTIMEZONE,
                 PlSqlLexer.SESSIONTZNAME, PlSqlLexer.SETS, PlSqlLexer.SETTINGS, PlSqlLexer.SET_TO_JOIN,
                 PlSqlLexer.SEVERE, PlSqlLexer.SHARED,
                 PlSqlLexer.SHARED_POOL, PlSqlLexer.SHOW, PlSqlLexer.SHRINK, PlSqlLexer.SHUTDOWN, PlSqlLexer.SIBLINGS,
                 PlSqlLexer.SID,
                 PlSqlLexer.SIGNAL_COMPONENT, PlSqlLexer.SIGNAL_FUNCTION, PlSqlLexer.SIGN, PlSqlLexer.SIMPLE,
                 PlSqlLexer.SINGLE, PlSqlLexer.SINGLETASK,
                 PlSqlLexer.SINH, PlSqlLexer.SIN, PlSqlLexer.SKIP_EXT_OPTIMIZER, PlSqlLexer.SKIP_,
                 PlSqlLexer.SKIP_UNQ_UNUSABLE_IDX, PlSqlLexer.SKIP_UNUSABLE_INDEXES,
                 PlSqlLexer.SMALLFILE, PlSqlLexer.SNAPSHOT, PlSqlLexer.SOME, PlSqlLexer.SORT, PlSqlLexer.SOUNDEX,
                 PlSqlLexer.SOURCE,
                 PlSqlLexer.SPACE_KEYWORD, PlSqlLexer.SPECIFICATION, PlSqlLexer.SPFILE, PlSqlLexer.SPLIT,
                 PlSqlLexer.SPREADSHEET, PlSqlLexer.SQLLDR,
                 PlSqlLexer.SQL, PlSqlLexer.SQL_TRACE, PlSqlLexer.SQL_MACRO, PlSqlLexer.SQRT, PlSqlLexer.STALE,
                 PlSqlLexer.STANDALONE,
                 PlSqlLexer.STANDBY_MAX_DATA_DELAY, PlSqlLexer.STANDBY, PlSqlLexer.STAR, PlSqlLexer.STAR_TRANSFORMATION,
                 PlSqlLexer.STARTUP, PlSqlLexer.STATEMENT_ID,
                 PlSqlLexer.STATEMENT_QUEUING, PlSqlLexer.STATEMENTS, PlSqlLexer.STATIC, PlSqlLexer.STATISTICS,
                 PlSqlLexer.STATS_BINOMIAL_TEST, PlSqlLexer.STATS_CROSSTAB,
                 PlSqlLexer.STATS_F_TEST, PlSqlLexer.STATS_KS_TEST, PlSqlLexer.STATS_MODE, PlSqlLexer.STATS_MW_TEST,
                 PlSqlLexer.STATS_ONE_WAY_ANOVA, PlSqlLexer.STATS_T_TEST_INDEP,
                 PlSqlLexer.STATS_T_TEST_INDEPU, PlSqlLexer.STATS_T_TEST_ONE, PlSqlLexer.STATS_T_TEST_PAIRED,
                 PlSqlLexer.STATS_WSR_TEST, PlSqlLexer.STDDEV, PlSqlLexer.STDDEV_POP,
                 PlSqlLexer.STDDEV_SAMP, PlSqlLexer.STOP, PlSqlLexer.STORAGE, PlSqlLexer.STORE, PlSqlLexer.STREAMS,
                 PlSqlLexer.STRICT,
                 PlSqlLexer.STRING, PlSqlLexer.STRIPE_COLUMNS, PlSqlLexer.STRIPE_WIDTH, PlSqlLexer.STRIP,
                 PlSqlLexer.STRUCTURE, PlSqlLexer.SUBMULTISET,
                 PlSqlLexer.SUBPARTITION, PlSqlLexer.SUBPARTITION_REL, PlSqlLexer.SUBPARTITIONS, PlSqlLexer.SUBQUERIES,
                 PlSqlLexer.SUBQUERY_PRUNING, PlSqlLexer.SUBSTITUTABLE,
                 PlSqlLexer.SUBSTR2, PlSqlLexer.SUBSTR4, PlSqlLexer.SUBSTRB, PlSqlLexer.SUBSTRC, PlSqlLexer.SUBSTR,
                 PlSqlLexer.SUCCESSFUL,
                 PlSqlLexer.SUMMARY, PlSqlLexer.SUM, PlSqlLexer.SUPPLEMENTAL, PlSqlLexer.SUSPEND,
                 PlSqlLexer.SWAP_JOIN_INPUTS, PlSqlLexer.SWITCH,
                 PlSqlLexer.SWITCHOVER, PlSqlLexer.SYNCHRONOUS, PlSqlLexer.SYNC, PlSqlLexer.SYS, PlSqlLexer.SYSASM,
                 PlSqlLexer.SYS_AUDIT,
                 PlSqlLexer.SYSAUX, PlSqlLexer.SYS_CHECKACL, PlSqlLexer.SYS_CONNECT_BY_PATH, PlSqlLexer.SYS_CONTEXT,
                 PlSqlLexer.SYSDATE, PlSqlLexer.SYSDBA,
                 PlSqlLexer.SYS_DBURIGEN, PlSqlLexer.SYS_DL_CURSOR, PlSqlLexer.SYS_DM_RXFORM_CHR,
                 PlSqlLexer.SYS_DM_RXFORM_NUM, PlSqlLexer.SYS_DOM_COMPARE, PlSqlLexer.SYS_DST_PRIM2SEC,
                 PlSqlLexer.SYS_DST_SEC2PRIM, PlSqlLexer.SYS_ET_BFILE_TO_RAW, PlSqlLexer.SYS_ET_BLOB_TO_IMAGE,
                 PlSqlLexer.SYS_ET_IMAGE_TO_BLOB, PlSqlLexer.SYS_ET_RAW_TO_BFILE, PlSqlLexer.SYS_EXTPDTXT,
                 PlSqlLexer.SYS_EXTRACT_UTC, PlSqlLexer.SYS_FBT_INSDEL, PlSqlLexer.SYS_FILTER_ACLS,
                 PlSqlLexer.SYS_FNMATCHES, PlSqlLexer.SYS_FNREPLACE, PlSqlLexer.SYS_GET_ACLIDS,
                 PlSqlLexer.SYS_GET_PRIVILEGES, PlSqlLexer.SYS_GETTOKENID, PlSqlLexer.SYS_GETXTIVAL,
                 PlSqlLexer.SYS_GUID, PlSqlLexer.SYS_MAKEXML, PlSqlLexer.SYS_MAKE_XMLNODEID,
                 PlSqlLexer.SYS_MKXMLATTR, PlSqlLexer.SYS_OP_ADT2BIN, PlSqlLexer.SYS_OP_ADTCONS,
                 PlSqlLexer.SYS_OP_ALSCRVAL, PlSqlLexer.SYS_OP_ATG, PlSqlLexer.SYS_OP_BIN2ADT,
                 PlSqlLexer.SYS_OP_BITVEC, PlSqlLexer.SYS_OP_BL2R, PlSqlLexer.SYS_OP_BLOOM_FILTER_LIST,
                 PlSqlLexer.SYS_OP_BLOOM_FILTER, PlSqlLexer.SYS_OP_C2C, PlSqlLexer.SYS_OP_CAST,
                 PlSqlLexer.SYS_OP_CEG, PlSqlLexer.SYS_OP_CL2C, PlSqlLexer.SYS_OP_COMBINED_HASH, PlSqlLexer.SYS_OP_COMP,
                 PlSqlLexer.SYS_OP_CONVERT, PlSqlLexer.SYS_OP_COUNTCHG,
                 PlSqlLexer.SYS_OP_CSCONV, PlSqlLexer.SYS_OP_CSCONVTEST, PlSqlLexer.SYS_OP_CSR,
                 PlSqlLexer.SYS_OP_CSX_PATCH, PlSqlLexer.SYS_OP_DECOMP, PlSqlLexer.SYS_OP_DESCEND,
                 PlSqlLexer.SYS_OP_DISTINCT, PlSqlLexer.SYS_OP_DRA, PlSqlLexer.SYS_OP_DUMP, PlSqlLexer.SYS_OP_DV_CHECK,
                 PlSqlLexer.SYS_OP_ENFORCE_NOT_NULL, PlSqlLexer.SYSOPER,
                 PlSqlLexer.SYS_OP_EXTRACT, PlSqlLexer.SYS_OP_GROUPING, PlSqlLexer.SYS_OP_GUID, PlSqlLexer.SYS_OP_IIX,
                 PlSqlLexer.SYS_OP_ITR, PlSqlLexer.SYS_OP_LBID,
                 PlSqlLexer.SYS_OP_LOBLOC2BLOB, PlSqlLexer.SYS_OP_LOBLOC2CLOB, PlSqlLexer.SYS_OP_LOBLOC2ID,
                 PlSqlLexer.SYS_OP_LOBLOC2NCLOB, PlSqlLexer.SYS_OP_LOBLOC2TYP, PlSqlLexer.SYS_OP_LSVI,
                 PlSqlLexer.SYS_OP_LVL, PlSqlLexer.SYS_OP_MAKEOID, PlSqlLexer.SYS_OP_MAP_NONNULL, PlSqlLexer.SYS_OP_MSR,
                 PlSqlLexer.SYS_OP_NICOMBINE, PlSqlLexer.SYS_OP_NIEXTRACT,
                 PlSqlLexer.SYS_OP_NII, PlSqlLexer.SYS_OP_NIX, PlSqlLexer.SYS_OP_NOEXPAND, PlSqlLexer.SYS_OP_NTCIMG,
                 PlSqlLexer.SYS_OP_NUMTORAW, PlSqlLexer.SYS_OP_OIDVALUE,
                 PlSqlLexer.SYS_OP_OPNSIZE, PlSqlLexer.SYS_OP_PAR_1, PlSqlLexer.SYS_OP_PARGID_1,
                 PlSqlLexer.SYS_OP_PARGID, PlSqlLexer.SYS_OP_PAR, PlSqlLexer.SYS_OP_PIVOT,
                 PlSqlLexer.SYS_OP_R2O, PlSqlLexer.SYS_OP_RAWTONUM, PlSqlLexer.SYS_OP_RDTM, PlSqlLexer.SYS_OP_REF,
                 PlSqlLexer.SYS_OP_RMTD, PlSqlLexer.SYS_OP_ROWIDTOOBJ,
                 PlSqlLexer.SYS_OP_RPB, PlSqlLexer.SYS_OPTLOBPRBSC, PlSqlLexer.SYS_OP_TOSETID, PlSqlLexer.SYS_OP_TPR,
                 PlSqlLexer.SYS_OP_TRTB, PlSqlLexer.SYS_OPTXICMP,
                 PlSqlLexer.SYS_OPTXQCASTASNQ, PlSqlLexer.SYS_OP_UNDESCEND, PlSqlLexer.SYS_OP_VECAND,
                 PlSqlLexer.SYS_OP_VECBIT, PlSqlLexer.SYS_OP_VECOR, PlSqlLexer.SYS_OP_VECXOR,
                 PlSqlLexer.SYS_OP_VERSION, PlSqlLexer.SYS_OP_VREF, PlSqlLexer.SYS_OP_VVD,
                 PlSqlLexer.SYS_OP_XMLCONS_FOR_CSX, PlSqlLexer.SYS_OP_XPTHATG, PlSqlLexer.SYS_OP_XPTHIDX,
                 PlSqlLexer.SYS_OP_XPTHOP, PlSqlLexer.SYS_OP_XTXT2SQLT, PlSqlLexer.SYS_ORDERKEY_DEPTH,
                 PlSqlLexer.SYS_ORDERKEY_MAXCHILD, PlSqlLexer.SYS_ORDERKEY_PARENT, PlSqlLexer.SYS_PARALLEL_TXN,
                 PlSqlLexer.SYS_PATHID_IS_ATTR, PlSqlLexer.SYS_PATHID_IS_NMSPC, PlSqlLexer.SYS_PATHID_LASTNAME,
                 PlSqlLexer.SYS_PATHID_LASTNMSPC, PlSqlLexer.SYS_PATH_REVERSE, PlSqlLexer.SYS_PXQEXTRACT,
                 PlSqlLexer.SYS_RID_ORDER, PlSqlLexer.SYS_ROW_DELTA, PlSqlLexer.SYS_SC_2_XMLT,
                 PlSqlLexer.SYS_SYNRCIREDO, PlSqlLexer.SYSTEM_DEFINED, PlSqlLexer.SYSTEM,
                 PlSqlLexer.SYSTIMESTAMP, PlSqlLexer.SYS_TYPEID, PlSqlLexer.SYS_UMAKEXML, PlSqlLexer.SYS_XMLANALYZE,
                 PlSqlLexer.SYS_XMLCONTAINS, PlSqlLexer.SYS_XMLCONV,
                 PlSqlLexer.SYS_XMLEXNSURI, PlSqlLexer.SYS_XMLGEN, PlSqlLexer.SYS_XMLI_LOC_ISNODE,
                 PlSqlLexer.SYS_XMLI_LOC_ISTEXT, PlSqlLexer.SYS_XMLINSTR, PlSqlLexer.SYS_XMLLOCATOR_GETSVAL,
                 PlSqlLexer.SYS_XMLNODEID_GETCID, PlSqlLexer.SYS_XMLNODEID_GETLOCATOR, PlSqlLexer.SYS_XMLNODEID_GETOKEY,
                 PlSqlLexer.SYS_XMLNODEID_GETPATHID, PlSqlLexer.SYS_XMLNODEID_GETPTRID, PlSqlLexer.SYS_XMLNODEID_GETRID,
                 PlSqlLexer.SYS_XMLNODEID_GETSVAL, PlSqlLexer.SYS_XMLNODEID_GETTID, PlSqlLexer.SYS_XMLNODEID,
                 PlSqlLexer.SYS_XMLT_2_SC, PlSqlLexer.SYS_XMLTRANSLATE, PlSqlLexer.SYS_XMLTYPE2SQL,
                 PlSqlLexer.SYS_XQ_ASQLCNV, PlSqlLexer.SYS_XQ_ATOMCNVCHK, PlSqlLexer.SYS_XQBASEURI,
                 PlSqlLexer.SYS_XQCASTABLEERRH, PlSqlLexer.SYS_XQCODEP2STR, PlSqlLexer.SYS_XQCODEPEQ,
                 PlSqlLexer.SYS_XQCON2SEQ, PlSqlLexer.SYS_XQCONCAT, PlSqlLexer.SYS_XQDELETE,
                 PlSqlLexer.SYS_XQDFLTCOLATION, PlSqlLexer.SYS_XQDOC, PlSqlLexer.SYS_XQDOCURI,
                 PlSqlLexer.SYS_XQDURDIV, PlSqlLexer.SYS_XQED4URI, PlSqlLexer.SYS_XQENDSWITH, PlSqlLexer.SYS_XQERRH,
                 PlSqlLexer.SYS_XQERR, PlSqlLexer.SYS_XQESHTMLURI,
                 PlSqlLexer.SYS_XQEXLOBVAL, PlSqlLexer.SYS_XQEXSTWRP, PlSqlLexer.SYS_XQEXTRACT,
                 PlSqlLexer.SYS_XQEXTRREF, PlSqlLexer.SYS_XQEXVAL, PlSqlLexer.SYS_XQFB2STR,
                 PlSqlLexer.SYS_XQFNBOOL, PlSqlLexer.SYS_XQFNCMP, PlSqlLexer.SYS_XQFNDATIM, PlSqlLexer.SYS_XQFNLNAME,
                 PlSqlLexer.SYS_XQFNNM, PlSqlLexer.SYS_XQFNNSURI,
                 PlSqlLexer.SYS_XQFNPREDTRUTH, PlSqlLexer.SYS_XQFNQNM, PlSqlLexer.SYS_XQFNROOT,
                 PlSqlLexer.SYS_XQFORMATNUM, PlSqlLexer.SYS_XQFTCONTAIN, PlSqlLexer.SYS_XQFUNCR,
                 PlSqlLexer.SYS_XQGETCONTENT, PlSqlLexer.SYS_XQINDXOF, PlSqlLexer.SYS_XQINSERT, PlSqlLexer.SYS_XQINSPFX,
                 PlSqlLexer.SYS_XQIRI2URI, PlSqlLexer.SYS_XQLANG,
                 PlSqlLexer.SYS_XQLLNMFRMQNM, PlSqlLexer.SYS_XQMKNODEREF, PlSqlLexer.SYS_XQNILLED,
                 PlSqlLexer.SYS_XQNODENAME, PlSqlLexer.SYS_XQNORMSPACE, PlSqlLexer.SYS_XQNORMUCODE,
                 PlSqlLexer.SYS_XQ_NRNG, PlSqlLexer.SYS_XQNSP4PFX, PlSqlLexer.SYS_XQNSPFRMQNM,
                 PlSqlLexer.SYS_XQPFXFRMQNM, PlSqlLexer.SYS_XQ_PKSQL2XML, PlSqlLexer.SYS_XQPOLYABS,
                 PlSqlLexer.SYS_XQPOLYADD, PlSqlLexer.SYS_XQPOLYCEL, PlSqlLexer.SYS_XQPOLYCSTBL,
                 PlSqlLexer.SYS_XQPOLYCST, PlSqlLexer.SYS_XQPOLYDIV, PlSqlLexer.SYS_XQPOLYFLR,
                 PlSqlLexer.SYS_XQPOLYMOD, PlSqlLexer.SYS_XQPOLYMUL, PlSqlLexer.SYS_XQPOLYRND,
                 PlSqlLexer.SYS_XQPOLYSQRT, PlSqlLexer.SYS_XQPOLYSUB, PlSqlLexer.SYS_XQPOLYUMUS,
                 PlSqlLexer.SYS_XQPOLYUPLS, PlSqlLexer.SYS_XQPOLYVEQ, PlSqlLexer.SYS_XQPOLYVGE,
                 PlSqlLexer.SYS_XQPOLYVGT, PlSqlLexer.SYS_XQPOLYVLE, PlSqlLexer.SYS_XQPOLYVLT,
                 PlSqlLexer.SYS_XQPOLYVNE, PlSqlLexer.SYS_XQREF2VAL, PlSqlLexer.SYS_XQRENAME, PlSqlLexer.SYS_XQREPLACE,
                 PlSqlLexer.SYS_XQRESVURI, PlSqlLexer.SYS_XQRNDHALF2EVN,
                 PlSqlLexer.SYS_XQRSLVQNM, PlSqlLexer.SYS_XQRYENVPGET, PlSqlLexer.SYS_XQRYVARGET,
                 PlSqlLexer.SYS_XQRYWRP, PlSqlLexer.SYS_XQSEQ2CON4XC, PlSqlLexer.SYS_XQSEQ2CON,
                 PlSqlLexer.SYS_XQSEQDEEPEQ, PlSqlLexer.SYS_XQSEQINSB, PlSqlLexer.SYS_XQSEQRM, PlSqlLexer.SYS_XQSEQRVS,
                 PlSqlLexer.SYS_XQSEQSUB, PlSqlLexer.SYS_XQSEQTYPMATCH,
                 PlSqlLexer.SYS_XQSTARTSWITH, PlSqlLexer.SYS_XQSTATBURI, PlSqlLexer.SYS_XQSTR2CODEP,
                 PlSqlLexer.SYS_XQSTRJOIN, PlSqlLexer.SYS_XQSUBSTRAFT, PlSqlLexer.SYS_XQSUBSTRBEF,
                 PlSqlLexer.SYS_XQTOKENIZE, PlSqlLexer.SYS_XQTREATAS, PlSqlLexer.SYS_XQ_UPKXML2SQL,
                 PlSqlLexer.SYS_XQXFORM, PlSqlLexer.TABLE, PlSqlLexer.TABLE_LOOKUP_BY_NL,
                 PlSqlLexer.TABLES, PlSqlLexer.TABLESPACE, PlSqlLexer.TABLESPACE_NO, PlSqlLexer.TABLE_STATS,
                 PlSqlLexer.TABNO, PlSqlLexer.TANH,
                 PlSqlLexer.TAN, PlSqlLexer.TBLORIDXPARTNUM, PlSqlLexer.TEMPFILE, PlSqlLexer.TEMPLATE,
                 PlSqlLexer.TEMPORARY, PlSqlLexer.TEMP_TABLE,
                 PlSqlLexer.TEST, PlSqlLexer.THAN, PlSqlLexer.THE, PlSqlLexer.THEN, PlSqlLexer.THREAD,
                 PlSqlLexer.THROUGH,
                 PlSqlLexer.TIME, PlSqlLexer.TIMING, PlSqlLexer.TIMEOUT, PlSqlLexer.TIMES, PlSqlLexer.TIMESTAMP,
                 PlSqlLexer.TIMEZONE_ABBR,
                 PlSqlLexer.TIMEZONE_HOUR, PlSqlLexer.TIMEZONE_MINUTE, PlSqlLexer.TIME_ZONE, PlSqlLexer.TIMEZONE_OFFSET,
                 PlSqlLexer.TIMEZONE_REGION, PlSqlLexer.TIV_GB,
                 PlSqlLexer.TIV_SSF, PlSqlLexer.TO_BINARY_DOUBLE, PlSqlLexer.TO_BINARY_FLOAT, PlSqlLexer.TO_BLOB,
                 PlSqlLexer.TO_CHAR, PlSqlLexer.TO_CLOB,
                 PlSqlLexer.TO_DATE, PlSqlLexer.TO_DSINTERVAL, PlSqlLexer.TO_LOB, PlSqlLexer.TO_MULTI_BYTE,
                 PlSqlLexer.TO_NCHAR, PlSqlLexer.TO_NCLOB,
                 PlSqlLexer.TO_NUMBER, PlSqlLexer.TOPLEVEL, PlSqlLexer.TO_SINGLE_BYTE, PlSqlLexer.TO_TIME,
                 PlSqlLexer.TO_TIMESTAMP, PlSqlLexer.TO_TIMESTAMP_TZ,
                 PlSqlLexer.TO_TIME_TZ, PlSqlLexer.TO_YMINTERVAL, PlSqlLexer.TRACE, PlSqlLexer.TRACING,
                 PlSqlLexer.TRACKING, PlSqlLexer.TRAILING,
                 PlSqlLexer.TRANSACTION, PlSqlLexer.TRANSFORM_DISTINCT_AGG, PlSqlLexer.TRANSITIONAL,
                 PlSqlLexer.TRANSITION, PlSqlLexer.TRANSLATE, PlSqlLexer.TREAT,
                 PlSqlLexer.TRIGGERS, PlSqlLexer.TRIM, PlSqlLexer.TRUE, PlSqlLexer.TRUNCATE, PlSqlLexer.TRUNC,
                 PlSqlLexer.TRUSTED,
                 PlSqlLexer.TUNING, PlSqlLexer.TX, PlSqlLexer.TYPE, PlSqlLexer.TYPES, PlSqlLexer.TZ_OFFSET,
                 PlSqlLexer.UB2,
                 PlSqlLexer.UBA, PlSqlLexer.UID, PlSqlLexer.UNARCHIVED, PlSqlLexer.UNBOUNDED, PlSqlLexer.UNBOUND,
                 PlSqlLexer.UNDER,
                 PlSqlLexer.UNDO, PlSqlLexer.UNDROP, PlSqlLexer.UNIFORM, PlSqlLexer.UNISTR, PlSqlLexer.UNLIMITED,
                 PlSqlLexer.UNLOAD,
                 PlSqlLexer.UNLOCK, PlSqlLexer.UNNEST_INNERJ_DISTINCT_VIEW, PlSqlLexer.UNNEST,
                 PlSqlLexer.UNNEST_NOSEMIJ_NODISTINCTVIEW, PlSqlLexer.UNNEST_SEMIJ_VIEW, PlSqlLexer.UNPACKED,
                 PlSqlLexer.UNPIVOT, PlSqlLexer.UNPROTECTED, PlSqlLexer.UNQUIESCE, PlSqlLexer.UNRECOVERABLE,
                 PlSqlLexer.UNRESTRICTED, PlSqlLexer.UNTIL,
                 PlSqlLexer.UNUSABLE, PlSqlLexer.UNUSED, PlSqlLexer.UPDATABLE, PlSqlLexer.UPDATED, PlSqlLexer.UPDATEXML,
                 PlSqlLexer.UPD_INDEXES,
                 PlSqlLexer.UPD_JOININDEX, PlSqlLexer.UPGRADE, PlSqlLexer.UPPER, PlSqlLexer.UPSERT, PlSqlLexer.UROWID,
                 PlSqlLexer.USAGE,
                 PlSqlLexer.USE_ANTI, PlSqlLexer.USE_CONCAT, PlSqlLexer.USE_HASH_AGGREGATION,
                 PlSqlLexer.USE_HASH_GBY_FOR_PUSHDOWN, PlSqlLexer.USE_HASH, PlSqlLexer.USE_INVISIBLE_INDEXES,
                 PlSqlLexer.USE_MERGE_CARTESIAN, PlSqlLexer.USE_MERGE, PlSqlLexer.USE, PlSqlLexer.USE_NL,
                 PlSqlLexer.USE_NL_WITH_INDEX, PlSqlLexer.USE_PRIVATE_OUTLINES,
                 PlSqlLexer.USER_DEFINED, PlSqlLexer.USERENV, PlSqlLexer.USERGROUP, PlSqlLexer.USER,
                 PlSqlLexer.USER_RECYCLEBIN, PlSqlLexer.USERS,
                 PlSqlLexer.USE_SEMI, PlSqlLexer.USE_STORED_OUTLINES, PlSqlLexer.USE_TTT_FOR_GSETS,
                 PlSqlLexer.USE_WEAK_NAME_RESL, PlSqlLexer.USING, PlSqlLexer.VALIDATE,
                 PlSqlLexer.VALIDATION, PlSqlLexer.VALUE, PlSqlLexer.VARIANCE, PlSqlLexer.VAR_POP, PlSqlLexer.VARRAY,
                 PlSqlLexer.VARRAYS,
                 PlSqlLexer.VAR_SAMP, PlSqlLexer.VARYING, PlSqlLexer.VECTOR_READ, PlSqlLexer.VECTOR_READ_TRACE,
                 PlSqlLexer.VERIFY, PlSqlLexer.VERSIONING,
                 PlSqlLexer.VERSION, PlSqlLexer.VERSIONS_ENDSCN, PlSqlLexer.VERSIONS_ENDTIME, PlSqlLexer.VERSIONS,
                 PlSqlLexer.VERSIONS_OPERATION, PlSqlLexer.VERSIONS_STARTSCN,
                 PlSqlLexer.VERSIONS_STARTTIME, PlSqlLexer.VERSIONS_XID, PlSqlLexer.VIRTUAL, PlSqlLexer.VISIBLE,
                 PlSqlLexer.VOLUME, PlSqlLexer.VSIZE,
                 PlSqlLexer.WAIT, PlSqlLexer.WALLET, PlSqlLexer.WELLFORMED, PlSqlLexer.WHENEVER, PlSqlLexer.WHEN,
                 PlSqlLexer.WHITESPACE,
                 PlSqlLexer.WIDTH_BUCKET, PlSqlLexer.WITHIN, PlSqlLexer.WITHOUT, PlSqlLexer.WORK, PlSqlLexer.WRAPPED,
                 PlSqlLexer.WRITE,
                 PlSqlLexer.XDB_FASTPATH_INSERT, PlSqlLexer.X_DYN_PRUNE, PlSqlLexer.XID, PlSqlLexer.XML2OBJECT,
                 PlSqlLexer.XMLATTRIBUTES, PlSqlLexer.XMLCAST,
                 PlSqlLexer.XMLCDATA, PlSqlLexer.XMLCOLATTVAL, PlSqlLexer.XMLCOMMENT, PlSqlLexer.XMLCONCAT,
                 PlSqlLexer.XMLDIFF, PlSqlLexer.XML_DML_RWT_STMT,
                 PlSqlLexer.XMLELEMENT, PlSqlLexer.XMLEXISTS2, PlSqlLexer.XMLEXISTS, PlSqlLexer.XMLFOREST,
                 PlSqlLexer.XMLINDEX_REWRITE_IN_SELECT, PlSqlLexer.XMLINDEX_REWRITE,
                 PlSqlLexer.XMLINDEX_SEL_IDX_TBL, PlSqlLexer.XMLISNODE, PlSqlLexer.XMLISVALID, PlSqlLexer.XML,
                 PlSqlLexer.XMLNAMESPACES, PlSqlLexer.XMLPARSE,
                 PlSqlLexer.XMLPATCH, PlSqlLexer.XMLPI, PlSqlLexer.XMLQUERY, PlSqlLexer.XMLQUERYVAL, PlSqlLexer.XMLROOT,
                 PlSqlLexer.XMLSCHEMA,
                 PlSqlLexer.XMLSERIALIZE, PlSqlLexer.XMLTABLE, PlSqlLexer.XMLTRANSFORMBLOB, PlSqlLexer.XMLTRANSFORM,
                 PlSqlLexer.XMLTYPE, PlSqlLexer.XPATHTABLE,
                 PlSqlLexer.XS_SYS_CONTEXT, PlSqlLexer.YEAR, PlSqlLexer.YES, PlSqlLexer.ZONE -> true;
            case PlSqlLexer.ACL, PlSqlLexer.ACROSS, PlSqlLexer.ACTION, PlSqlLexer.ACTIONS, PlSqlLexer.ACTIVE,
                 PlSqlLexer.ACTIVE_DATA,
                 PlSqlLexer.ACTIVITY, PlSqlLexer.ADAPTIVE_PLAN, PlSqlLexer.ADVANCED, PlSqlLexer.AFD_DISKSTRING,
                 PlSqlLexer.ALTERNATE, PlSqlLexer.ALGORITHM,
                 PlSqlLexer.ANALYTIC, PlSqlLexer.ANCESTOR, PlSqlLexer.ANOMALY, PlSqlLexer.ANSI_REARCH,
                 PlSqlLexer.APPLICATION, PlSqlLexer.APPROX_COUNT_DISTINCT,
                 PlSqlLexer.ARCHIVAL, PlSqlLexer.ARCHIVED, PlSqlLexer.ASIS, PlSqlLexer.ASSIGN, PlSqlLexer.AUTO_LOGIN,
                 PlSqlLexer.AUTO_REOPTIMIZE,
                 PlSqlLexer.AVRO, PlSqlLexer.BACKGROUND, PlSqlLexer.BACKUPS, PlSqlLexer.BATCHSIZE,
                 PlSqlLexer.BATCH_TABLE_ACCESS_BY_ROWID, PlSqlLexer.BEGINNING,
                 PlSqlLexer.BEQUEATH, PlSqlLexer.BITMAP_AND, PlSqlLexer.BLOCKCHAIN, PlSqlLexer.BSON, PlSqlLexer.CACHING,
                 PlSqlLexer.CALCULATED,
                 PlSqlLexer.CALLBACK, PlSqlLexer.CAPACITY, PlSqlLexer.CAPTION, PlSqlLexer.CDBDEFAULT,
                 PlSqlLexer.CLASSIFICATION, PlSqlLexer.CLASSIFIER,
                 PlSqlLexer.CLAUSE, PlSqlLexer.CLEAN, PlSqlLexer.CLEANUP, PlSqlLexer.CLIENT, PlSqlLexer.CLUSTERING,
                 PlSqlLexer.CLUSTER_DETAILS,
                 PlSqlLexer.CLUSTER_DISTANCE, PlSqlLexer.COLLATE, PlSqlLexer.COLLATION, PlSqlLexer.COMMON,
                 PlSqlLexer.COMMON_DATA, PlSqlLexer.COMPONENT,
                 PlSqlLexer.COMPONENTS, PlSqlLexer.CONDITION, PlSqlLexer.CONDITIONAL, PlSqlLexer.CONTAINERS,
                 PlSqlLexer.CONTAINERS_DEFAULT, PlSqlLexer.CONTAINER_DATA,
                 PlSqlLexer.CONTAINER_MAP, PlSqlLexer.CONVERSION, PlSqlLexer.CON_DBID_TO_ID, PlSqlLexer.CON_GUID_TO_ID,
                 PlSqlLexer.CON_ID, PlSqlLexer.CON_NAME_TO_ID,
                 PlSqlLexer.CON_UID_TO_ID, PlSqlLexer.COOKIE, PlSqlLexer.COPY, PlSqlLexer.CREATE_FILE_DEST,
                 PlSqlLexer.CREDENTIAL, PlSqlLexer.CRITICAL,
                 PlSqlLexer.CUBE_AJ, PlSqlLexer.CUBE_SJ, PlSqlLexer.DATAMOVEMENT, PlSqlLexer.DATAOBJ_TO_MAT_PARTITION,
                 PlSqlLexer.DATAPUMP, PlSqlLexer.DATA_SECURITY_REWRITE_LIMIT,
                 PlSqlLexer.DAYS, PlSqlLexer.DB_UNIQUE_NAME, PlSqlLexer.DECORRELATE, PlSqlLexer.DEFAULT_CREDENTIAL,
                 PlSqlLexer.DEFAULT_COLLATION, PlSqlLexer.DEFINE,
                 PlSqlLexer.DEFINITION, PlSqlLexer.DELEGATE, PlSqlLexer.DELETE_ALL, PlSqlLexer.DESCRIPTION,
                 PlSqlLexer.DESTROY, PlSqlLexer.DIMENSIONS,
                 PlSqlLexer.DISABLE_ALL, PlSqlLexer.DISABLE_PARALLEL_DML, PlSqlLexer.DISCARD, PlSqlLexer.DISTRIBUTE,
                 PlSqlLexer.DUPLICATE, PlSqlLexer.DUPLICATED,
                 PlSqlLexer.DV, PlSqlLexer.EDITIONABLE, PlSqlLexer.ELIM_GROUPBY, PlSqlLexer.EM, PlSqlLexer.ENABLE_ALL,
                 PlSqlLexer.ENABLE_PARALLEL_DML,
                 PlSqlLexer.EQUIPART, PlSqlLexer.EVAL, PlSqlLexer.EVALUATE, PlSqlLexer.EXISTING, PlSqlLexer.EXPRESS,
                 PlSqlLexer.EXTENDED,
                 PlSqlLexer.EXTRACTCLOBXML, PlSqlLexer.FACTOR, PlSqlLexer.FAILOVER, PlSqlLexer.FAILURE,
                 PlSqlLexer.FAMILY, PlSqlLexer.FAR,
                 PlSqlLexer.FASTSTART, PlSqlLexer.FEATURE, PlSqlLexer.FEATURE_DETAILS, PlSqlLexer.FETCH,
                 PlSqlLexer.FILE_NAME_CONVERT, PlSqlLexer.FILEGROUP,
                 PlSqlLexer.FIXED_VIEW_DATA, PlSqlLexer.FLEX, PlSqlLexer.FORMAT, PlSqlLexer.FTP,
                 PlSqlLexer.GATHER_OPTIMIZER_STATISTICS, PlSqlLexer.GET,
                 PlSqlLexer.HALF_YEARS, PlSqlLexer.HASHING, PlSqlLexer.HIER_ORDER, PlSqlLexer.HIERARCHICAL,
                 PlSqlLexer.HOURS, PlSqlLexer.HTTP,
                 PlSqlLexer.H_LETTER, PlSqlLexer.IDLE, PlSqlLexer.ILM, PlSqlLexer.IMMUTABLE, PlSqlLexer.INACTIVE,
                 PlSqlLexer.INACTIVE_ACCOUNT_TIME,
                 PlSqlLexer.INDEXING, PlSqlLexer.INHERIT, PlSqlLexer.INMEMORY, PlSqlLexer.INMEMORY_PRUNING,
                 PlSqlLexer.INPLACE, PlSqlLexer.INTERLEAVED,
                 PlSqlLexer.ISOLATE, PlSqlLexer.IS_LEAF, PlSqlLexer.JSON, PlSqlLexer.JSONGET, PlSqlLexer.JSONPARSE,
                 PlSqlLexer.JSON_ARRAY,
                 PlSqlLexer.JSON_ARRAYAGG, PlSqlLexer.JSON_EQUAL, PlSqlLexer.JSON_EXISTS, PlSqlLexer.JSON_EXISTS2,
                 PlSqlLexer.JSON_OBJECT, PlSqlLexer.JSON_OBJECTAGG,
                 PlSqlLexer.JSON_QUERY, PlSqlLexer.JSON_SERIALIZE, PlSqlLexer.JSON_TABLE, PlSqlLexer.JSON_TEXTCONTAINS,
                 PlSqlLexer.JSON_TEXTCONTAINS2, PlSqlLexer.JSON_VALUE,
                 PlSqlLexer.KEYSTORE, PlSqlLexer.LABEL, PlSqlLexer.LAX, PlSqlLexer.LEAD_CDB, PlSqlLexer.LEAD_CDB_URI,
                 PlSqlLexer.LEVEL_NAME,
                 PlSqlLexer.LIFECYCLE, PlSqlLexer.LINEAR, PlSqlLexer.LOCKDOWN, PlSqlLexer.LOCKING, PlSqlLexer.LOGMINING,
                 PlSqlLexer.LOST,
                 PlSqlLexer.MANDATORY, PlSqlLexer.MAP, PlSqlLexer.MATCH, PlSqlLexer.MATCHES, PlSqlLexer.MATCH_NUMBER,
                 PlSqlLexer.MATCH_RECOGNIZE,
                 PlSqlLexer.MAX_SHARED_TEMP_SIZE, PlSqlLexer.MEMCOMPRESS, PlSqlLexer.METADATA,
                 PlSqlLexer.MEMBER_CAPTION, PlSqlLexer.MEMBER_DESCRIPTION, PlSqlLexer.MEMBER_NAME,
                 PlSqlLexer.MEMBER_UNIQUE_NAME, PlSqlLexer.MINUTES, PlSqlLexer.MODEL_NB, PlSqlLexer.MODEL_SV,
                 PlSqlLexer.MODIFICATION, PlSqlLexer.MODULE,
                 PlSqlLexer.MONTHS, PlSqlLexer.MULTIDIMENSIONAL, PlSqlLexer.NEG, PlSqlLexer.NOCOPY, PlSqlLexer.NOKEEP,
                 PlSqlLexer.NONEDITIONABLE,
                 PlSqlLexer.NOPARTITION, PlSqlLexer.NORELOCATE, PlSqlLexer.NOREPLAY, PlSqlLexer.NO_ADAPTIVE_PLAN,
                 PlSqlLexer.NO_ANSI_REARCH, PlSqlLexer.NO_AUTO_REOPTIMIZE,
                 PlSqlLexer.NO_BATCH_TABLE_ACCESS_BY_ROWID, PlSqlLexer.NO_CLUSTERING, PlSqlLexer.NO_COMMON_DATA,
                 PlSqlLexer.NO_DATA_SECURITY_REWRITE, PlSqlLexer.NO_DECORRELATE, PlSqlLexer.NO_ELIM_GROUPBY,
                 PlSqlLexer.NO_GATHER_OPTIMIZER_STATISTICS, PlSqlLexer.NO_INMEMORY, PlSqlLexer.NO_INMEMORY_PRUNING,
                 PlSqlLexer.NO_OBJECT_LINK, PlSqlLexer.NO_PARTIAL_JOIN, PlSqlLexer.NO_PARTIAL_ROLLUP_PUSHDOWN,
                 PlSqlLexer.NO_PQ_CONCURRENT_UNION, PlSqlLexer.NO_PQ_REPLICATE, PlSqlLexer.NO_PQ_SKEW,
                 PlSqlLexer.NOPROMPT, PlSqlLexer.NO_PX_FAULT_TOLERANCE, PlSqlLexer.NO_ROOT_SW_FOR_LOCAL,
                 PlSqlLexer.NO_SQL_TRANSLATION, PlSqlLexer.NO_USE_CUBE, PlSqlLexer.NO_USE_VECTOR_AGGREGATION,
                 PlSqlLexer.NO_VECTOR_TRANSFORM, PlSqlLexer.NO_VECTOR_TRANSFORM_DIMS,
                 PlSqlLexer.NO_VECTOR_TRANSFORM_FACT,
                 PlSqlLexer.NO_ZONEMAP, PlSqlLexer.OBJ_ID, PlSqlLexer.OFFSET, PlSqlLexer.OLS, PlSqlLexer.OMIT,
                 PlSqlLexer.ONE,
                 PlSqlLexer.ORACLE_DATAPUMP, PlSqlLexer.ORACLE_HDFS, PlSqlLexer.ORACLE_HIVE, PlSqlLexer.ORACLE_LOADER,
                 PlSqlLexer.ORA_CHECK_ACL, PlSqlLexer.ORA_CHECK_PRIVILEGE,
                 PlSqlLexer.ORA_CLUSTERING, PlSqlLexer.ORA_INVOKING_USER, PlSqlLexer.ORA_INVOKING_USERID,
                 PlSqlLexer.ORA_INVOKING_XS_USER, PlSqlLexer.ORA_INVOKING_XS_USER_GUID, PlSqlLexer.ORA_RAWCOMPARE,
                 PlSqlLexer.ORA_RAWCONCAT, PlSqlLexer.ORA_WRITE_TIME, PlSqlLexer.PARENT_LEVEL_NAME,
                 PlSqlLexer.PARENT_UNIQUE_NAME, PlSqlLexer.PASSWORD_ROLLOVER_TIME, PlSqlLexer.PARTIAL,
                 PlSqlLexer.PARTIAL_JOIN, PlSqlLexer.PARTIAL_ROLLUP_PUSHDOWN, PlSqlLexer.PAST, PlSqlLexer.PATCH,
                 PlSqlLexer.PATH_PREFIX, PlSqlLexer.PATTERN,
                 PlSqlLexer.PER, PlSqlLexer.PERIOD, PlSqlLexer.PERIOD_KEYWORD, PlSqlLexer.PERMUTE, PlSqlLexer.PLUGGABLE,
                 PlSqlLexer.POOL_16K,
                 PlSqlLexer.POOL_2K, PlSqlLexer.POOL_32K, PlSqlLexer.POOL_4K, PlSqlLexer.POOL_8K,
                 PlSqlLexer.PQ_CONCURRENT_UNION, PlSqlLexer.PQ_DISTRIBUTE_WINDOW,
                 PlSqlLexer.PQ_FILTER, PlSqlLexer.PQ_REPLICATE, PlSqlLexer.PQ_SKEW, PlSqlLexer.PRELOAD,
                 PlSqlLexer.PRETTY, PlSqlLexer.PREV,
                 PlSqlLexer.PRINTBLOBTOCLOB, PlSqlLexer.PRIORITY, PlSqlLexer.PRIVILEGED, PlSqlLexer.PROPERTY,
                 PlSqlLexer.PROTOCOL, PlSqlLexer.PROXY,
                 PlSqlLexer.PRUNING, PlSqlLexer.PX_FAULT_TOLERANCE, PlSqlLexer.QUARTERS, PlSqlLexer.QUOTAGROUP,
                 PlSqlLexer.REALM, PlSqlLexer.REDEFINE,
                 PlSqlLexer.RELOCATE, PlSqlLexer.REMOTE, PlSqlLexer.RESTART, PlSqlLexer.ROLESET,
                 PlSqlLexer.ROWID_MAPPING_TABLE, PlSqlLexer.RUNNING,
                 PlSqlLexer.SAVE, PlSqlLexer.SCRUB, PlSqlLexer.SDO_GEOM_MBR, PlSqlLexer.SECONDS, PlSqlLexer.SECRET,
                 PlSqlLexer.SERIAL,
                 PlSqlLexer.SERVICES, PlSqlLexer.SERVICE_NAME_CONVERT, PlSqlLexer.SHARDED, PlSqlLexer.SHARING,
                 PlSqlLexer.SHELFLIFE, PlSqlLexer.SITE,
                 PlSqlLexer.SOURCE_FILE_DIRECTORY, PlSqlLexer.SOURCE_FILE_NAME_CONVERT,
                 PlSqlLexer.SQL_TRANSLATION_PROFILE, PlSqlLexer.STANDARD, PlSqlLexer.STANDARD_HASH, PlSqlLexer.STANDBYS,
                 PlSqlLexer.STATE, PlSqlLexer.STATEMENT, PlSqlLexer.STREAM, PlSqlLexer.SUBSCRIBE, PlSqlLexer.SUBSET,
                 PlSqlLexer.SUCCESS,
                 PlSqlLexer.SYSBACKUP, PlSqlLexer.SYSDG, PlSqlLexer.SYSGUID, PlSqlLexer.SYSKM, PlSqlLexer.SYSOBJ,
                 PlSqlLexer.SYS_CHECK_PRIVILEGE,
                 PlSqlLexer.SYS_GET_COL_ACLIDS, PlSqlLexer.SYS_MKXTI, PlSqlLexer.SYS_OP_CYCLED_SEQ,
                 PlSqlLexer.SYS_OP_HASH, PlSqlLexer.SYS_OP_KEY_VECTOR_CREATE, PlSqlLexer.SYS_OP_KEY_VECTOR_FILTER,
                 PlSqlLexer.SYS_OP_KEY_VECTOR_FILTER_LIST, PlSqlLexer.SYS_OP_KEY_VECTOR_SUCCEEDED,
                 PlSqlLexer.SYS_OP_KEY_VECTOR_USE, PlSqlLexer.SYS_OP_PART_ID, PlSqlLexer.SYS_OP_ZONE_ID,
                 PlSqlLexer.SYS_RAW_TO_XSID,
                 PlSqlLexer.SYS_XSID_TO_RAW, PlSqlLexer.SYS_ZMAP_FILTER, PlSqlLexer.SYS_ZMAP_REFRESH, PlSqlLexer.TAG,
                 PlSqlLexer.TEXT, PlSqlLexer.TIER,
                 PlSqlLexer.TIES, PlSqlLexer.TO_ACLID, PlSqlLexer.TRANSFORM, PlSqlLexer.TRANSLATION, PlSqlLexer.TRUST,
                 PlSqlLexer.UCS2,
                 PlSqlLexer.UNCONDITIONAL, PlSqlLexer.UNITE, PlSqlLexer.UNMATCHED, PlSqlLexer.UNPLUG,
                 PlSqlLexer.UNSUBSCRIBE, PlSqlLexer.USABLE,
                 PlSqlLexer.USER_DATA, PlSqlLexer.USER_TABLESPACES, PlSqlLexer.USE_CUBE,
                 PlSqlLexer.USE_HIDDEN_PARTITIONS, PlSqlLexer.USE_VECTOR_AGGREGATION, PlSqlLexer.USING_NO_EXPAND,
                 PlSqlLexer.UTF16BE, PlSqlLexer.UTF16LE, PlSqlLexer.UTF32, PlSqlLexer.UTF8, PlSqlLexer.V1,
                 PlSqlLexer.V2,
                 PlSqlLexer.VALIDATE_CONVERSION, PlSqlLexer.VALID_TIME_END, PlSqlLexer.VECTOR_TRANSFORM,
                 PlSqlLexer.VECTOR_TRANSFORM_DIMS, PlSqlLexer.VECTOR_TRANSFORM_FACT, PlSqlLexer.VERIFIER,
                 PlSqlLexer.VIOLATION, PlSqlLexer.VISIBILITY, PlSqlLexer.WEEK, PlSqlLexer.WEEKS, PlSqlLexer.WITH_PLSQL,
                 PlSqlLexer.WRAPPER,
                 PlSqlLexer.XS, PlSqlLexer.YEARS, PlSqlLexer.ZONEMAP, PlSqlLexer.DEFAULTIF, PlSqlLexer.LLS,
                 PlSqlLexer.ENCLOSED,
                 PlSqlLexer.TERMINATED, PlSqlLexer.OPTIONALLY, PlSqlLexer.LRTRIM, PlSqlLexer.NOTRIM, PlSqlLexer.LDRTRIM,
                 PlSqlLexer.DATE_FORMAT,
                 PlSqlLexer.MASK, PlSqlLexer.TRANSFORMS, PlSqlLexer.LOBFILE, PlSqlLexer.STARTOF,
                 PlSqlLexer.CHARACTERSET, PlSqlLexer.RECORDS,
                 PlSqlLexer.FIXED, PlSqlLexer.DELIMITED, PlSqlLexer.XMLTAG, PlSqlLexer.PREPROCESSOR,
                 PlSqlLexer.TERRITORY, PlSqlLexer.LITTLE,
                 PlSqlLexer.BIG, PlSqlLexer.ENDIAN, PlSqlLexer.BYTEORDERMARK, PlSqlLexer.NOCHECK, PlSqlLexer.SIZES,
                 PlSqlLexer.ARE,
                 PlSqlLexer.BYTES, PlSqlLexer.CHARACTERS, PlSqlLexer.READSIZE, PlSqlLexer.DISABLE_DIRECTORY_LINK_CHECK,
                 PlSqlLexer.DATE_CACHE, PlSqlLexer.FIELD_NAMES,
                 PlSqlLexer.FILES, PlSqlLexer.IO_OPTIONS, PlSqlLexer.DIRECTIO, PlSqlLexer.NODIRECTIO,
                 PlSqlLexer.DNFS_ENABLE, PlSqlLexer.DNFS_DISABLE,
                 PlSqlLexer.DNFS_READBUFFERS, PlSqlLexer.NOBADFILE, PlSqlLexer.BADFILE, PlSqlLexer.NODISCARDFILE,
                 PlSqlLexer.DISCARDFILE, PlSqlLexer.NOLOGFILE,
                 PlSqlLexer.FIELDS, PlSqlLexer.IGNORE_CHARS_AFTER_EOR, PlSqlLexer.CSV, PlSqlLexer.EMBEDDED,
                 PlSqlLexer.OVERRIDE, PlSqlLexer.THESE,
                 PlSqlLexer.FIELD, PlSqlLexer.NONULLIF, PlSqlLexer.POSITION, PlSqlLexer.NEWLINE_, PlSqlLexer.DETECTED,
                 PlSqlLexer.UNSIGNED,
                 PlSqlLexer.ZONED, PlSqlLexer.ORACLE_DATE, PlSqlLexer.ORACLE_NUMBER, PlSqlLexer.COUNTED,
                 PlSqlLexer.VARRAW, PlSqlLexer.VARCHARC,
                 PlSqlLexer.VARRAWC -> true;
            case PlSqlLexer.ABSENT, PlSqlLexer.A_LETTER, PlSqlLexer.AGENT, PlSqlLexer.AGGREGATE,
                 PlSqlLexer.AUTONOMOUS_TRANSACTION, PlSqlLexer.BACKINGFILE,
                 PlSqlLexer.BINARY_INTEGER, PlSqlLexer.BOOLEAN, PlSqlLexer.C_LETTER, PlSqlLexer.CHAR,
                 PlSqlLexer.CLUSTER, PlSqlLexer.CONSTRUCTOR,
                 PlSqlLexer.CUSTOMDATUM, PlSqlLexer.CASESENSITIVE, PlSqlLexer.DECIMAL, PlSqlLexer.DELETE,
                 PlSqlLexer.DETERMINISTIC, PlSqlLexer.DSINTERVAL_UNCONSTRAINED,
                 PlSqlLexer.E_LETTER, PlSqlLexer.ERR, PlSqlLexer.EXCEPTION, PlSqlLexer.EXCEPTION_INIT,
                 PlSqlLexer.EXISTS, PlSqlLexer.EXIT,
                 PlSqlLexer.FILESTORE, PlSqlLexer.FLOAT, PlSqlLexer.FORALL, PlSqlLexer.G_LETTER, PlSqlLexer.INDICES,
                 PlSqlLexer.INOUT,
                 PlSqlLexer.INTEGER, PlSqlLexer.JSON_TRANSFORM, PlSqlLexer.K_LETTER, PlSqlLexer.LANGUAGE,
                 PlSqlLexer.LONG, PlSqlLexer.LOOP,
                 PlSqlLexer.MOUNTPOINT, PlSqlLexer.M_LETTER, PlSqlLexer.MISSING, PlSqlLexer.MISMATCH, PlSqlLexer.NUMBER,
                 PlSqlLexer.ORADATA,
                 PlSqlLexer.OSERROR, PlSqlLexer.OUT, PlSqlLexer.OVERRIDING, PlSqlLexer.P_LETTER,
                 PlSqlLexer.PARALLEL_ENABLE, PlSqlLexer.PIPELINED,
                 PlSqlLexer.PLS_INTEGER, PlSqlLexer.PMEM, PlSqlLexer.POSITIVE, PlSqlLexer.POSITIVEN, PlSqlLexer.PRAGMA,
                 PlSqlLexer.PUBLIC,
                 PlSqlLexer.RAISE, PlSqlLexer.RAW, PlSqlLexer.RECORD, PlSqlLexer.RENAME, PlSqlLexer.RESTRICT_REFERENCES,
                 PlSqlLexer.RESULT,
                 PlSqlLexer.SDO_GEOMETRY, PlSqlLexer.SELF, PlSqlLexer.SERIALLY_REUSABLE, PlSqlLexer.SET,
                 PlSqlLexer.SHARDSPACE, PlSqlLexer.SIGNTYPE,
                 PlSqlLexer.SIMPLE_INTEGER, PlSqlLexer.SMALLINT, PlSqlLexer.SQLDATA, PlSqlLexer.SQLERROR,
                 PlSqlLexer.SUBTYPE, PlSqlLexer.T_LETTER,
                 PlSqlLexer.TIMESTAMP_LTZ_UNCONSTRAINED, PlSqlLexer.TIMESTAMP_TZ_UNCONSTRAINED,
                 PlSqlLexer.TIMESTAMP_UNCONSTRAINED, PlSqlLexer.TRIGGER, PlSqlLexer.VARCHAR, PlSqlLexer.VARCHAR2,
                 PlSqlLexer.VARIABLE, PlSqlLexer.WARNING, PlSqlLexer.WHILE, PlSqlLexer.XMLAGG,
                 PlSqlLexer.YMINTERVAL_UNCONSTRAINED, PlSqlLexer.REGR_,
                 PlSqlLexer.VAR_, PlSqlLexer.COVAR_ -> true;
            default -> false;
        };
    }

    public boolean isReservedKeywords(String s) {
        initReservedSet();
        return reservedSet.contains(s.toUpperCase());
    }

    private void initReservedSet() {
        if (reservedSet != null) {
            return;
        }
        reservedSet = new HashSet<>(RESERVED_WORDS);
    }
}